### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by T4ge** [CJMinecraft01/DoubleSlabs#1]
https://pastebin.com/raw/npdatZEV
Not quite sure what caused this. Suspecting it could be a coremod or wrong Forge version.
I don't have much information as this was discovered during debugging only logs for a friend.
Will gladly assist more if additional information is  required.

**Comment by CJMinecraft01** [comment]
From the error file you've gave, I can identify that it more than likely is my mod (sorry). 
`| LE    | doubleslabs                       | 0.0.2                    | DoubleSlabs-1.12-0.0.2.jar                        | None                                     |`
suggests that there was a loading error when loading the double slabs jar. I have (I believe) tracked down the issue, and it's a really simple fix (quite an embarrassing thing I forgot to do I think) so this will be patched in the next release which I'll be dropping soon.

**Comment by CJMinecraft01** [comment]
Should be resolved in the latest update
