### ISSUE TITLE
OpenGL Error 1281 With Current Mods

### ISSUE THREAD

**Issue by EldritchScream** [CJMinecraft01/DoubleSlabs#101]
I'm currently using the newest version of DoubleSlabs and these mods: https://imgur.com/a/arRx2Qv , most of which are from Serilum's "The Vanilla Experience" modpack (https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience). I'm getting an OpenGL Error 1281 Removing AutoRegLib from the mods, or using an older version of DoubleSlabs (3.2.0) does not fix the issue. 

Error only occurs when the vertical slab is rendered, when I turn away from the slab I don't get the error message.
Here are some screenshots: https://imgur.com/a/OalHmXr

**Comment by CJMinecraft01** [comment]
Hi! Thanks for reporting the issue. From what I've heard, this issue only occurs when OptiFine is installed. I'm going to investigate further as I've noticed quite a few issues when using OptiFine with vertical slabs so I'll keep you posted.

**Comment by halvors** [comment]
+1 I am also experiencing this issue, would be great if i could continue to use this with Optifine :)

**Comment by CJMinecraft01** [comment]
Do you have render regions enabled?

**Comment by halvors** [comment]
@halvors Yes, is that the issue?

**Comment by CJMinecraft01** [comment]
Apologies for the extremely long delay in responding.. I have some fantastic news though, this is finally fixed!!! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
