### ISSUE TITLE
Crash when placed on Quark Paper panes.

### ISSUE THREAD

**Issue by IoanCiobanescu** [CJMinecraft01/DoubleSlabs#103]
This is a weird one to report, since I wasn't there to see it happen, but my server is clearly suffering the consequences of it. Someone placed a vertical slab of some kind next to a Paper Pane from Quark...so I've been told. Whenever that chunk is loaded, the server crashes with this being sent out in the console.

14.08 21:03:14 [Server] Server thread/ERROR Encountered an unexpected exception
14.08 21:03:14 [Server] INFO net.minecraft.util.ReportedException: Ticking entity
14.08 21:03:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
14.08 21:03:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
14.08 21:03:14 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=double, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=quark:paper_wall_big, properties=[east, north, south, west]}
14.08 21:03:14 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
14.08 21:03:14 [Server] INFO at cjminecraft.doubleslabs.blocks.BlockVerticalSlab.canBeConnectedTo(BlockVerticalSlab.java:792) ~[BlockVerticalSlab.class:0.10.0]
14.08 21:03:14 [Server] INFO at vazkii.quark.base.block.BlockQuarkPane.canPaneConnectTo(BlockQuarkPane.java:238) ~[BlockQuarkPane.class:?]
14.08 21:03:14 [Server] INFO at vazkii.quark.base.block.BlockQuarkPane.func_176221_a(BlockQuarkPane.java:115) ~[BlockQuarkPane.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423) ~[awu$a.class:?]
14.08 21:03:14 [Server] INFO at vazkii.quark.base.block.BlockQuarkPane.func_185477_a(BlockQuarkPane.java:60) ~[BlockQuarkPane.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451) ~[awu$a.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.world.World.func_191504_a(World.java:1341) ~[amu.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.world.World.func_184144_a(World.java:1365) ~[amu.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.Entity.func_70091_d(Entity.java:721) ~[vg.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958) ~[vp.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393) ~[vp.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) ~[ade.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223) ~[adt.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) ~[ade.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
14.08 21:03:14 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
14.08 21:03:16 [Multicraft] Skipped 9 lines due to rate limit (30/s)
14.08 21:03:16 [Server] Server thread/INFO [FML]: Unloading dimension 0
14.08 21:03:21 [Server] Server thread/INFO [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by IoanCiobanescu** [comment]
This happens in singleplayer when I replicated the process of placing the slab on the paper pane.

The game crashed whilst ticking particle
Error: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=double, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=quark:paper_wall_big, properties=[east, north, south, west]}

**Comment by CJMinecraft01** [comment]
Hi there, my sincerest apologies for the delay.. Would you mind testing this in the latest version please?

**Comment by IoanCiobanescu** [comment]
Ah, I should've mentioned this earlier, but after an update (forgot from which end), this bug ended up getting fixed. So this isn't a problem anymore.

**Comment by CJMinecraft01** [comment]
Thanks for getting back to me and again, sorry for the delay
