### ISSUE TITLE
Crash when you break vertical slabs!

### ISSUE THREAD

**Issue by BluEagle-Dev** [CJMinecraft01/DoubleSlabs#107]
i don't know what to add more then that, it just crashes when i break a vertical slab

Im on version 1.12.2 of the game!

**Comment by CJMinecraft01** [comment]
Could you provide the crash log please?

**Comment by BluEagle-Dev** [comment]
Yes working on it

**Comment by BluEagle-Dev** [comment]
here is the crash log:  https://pastebin.com/AWXdHy2N

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version :)

**Comment by BluEagle-Dev** [comment]
Ok, thank you SO much! I can't live without this mod
