### ISSUE TITLE
Game crash when breaking double oak slab

### ISSUE THREAD

**Issue by Naxanria** [CJMinecraft01/DoubleSlabs#11]
[crash-2020-03-07_14.07.46-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4301834/crash-2020-03-07_14.07.46-client.txt)

A spruce/oak combo didnt crash. Using an axe didnt crash, but pickaxe did.

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version
