### ISSUE TITLE
Doubleslab schematic crash Valhelsia Origins

### ISSUE THREAD

**Issue by OiJockey** [CJMinecraft01/DoubleSlabs#110]
The same issue was in the last verison and now its in 1.1.0 verison of Origins
When doing a build with doubleslabs and saving it to a schematic, when loading it into a server or just deploying, it will crash the entire game. Had a similar issue the second time as well but without doubleslabs and it was with fairylights. 
https://gist.github.com/OiJockey/9d3e1713b198de9699c6acb363f470d7

**Comment by CJMinecraft01** [comment]
I believe the issue may be due to how create handles rendering of processing of schematics but I will try and see if I can fix this on my end :)

**Comment by OiJockey** [comment]
Any update on this bug?

**Comment by CJMinecraft01** [comment]
This should hopefully be fixed in the latest version :)
