### ISSUE TITLE
Compat w/ Block Carpentry

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#112]
[Block Carpentry](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry) is a new mod recently released for 1.15.2 that adds a slab that can be placed horizontally or vertically and take on the texture of any block when right-clicked with said block. Is support for this mod possible?

**Comment by CJMinecraft01** [comment]
Added in the latest version :)

**Comment by WenXin20** [comment]
The mod update their slab placement logic and is now crashing in the latest version according to this bug report: PianoManu/BlockCarpentry#12

**Comment by xAlicatt** [comment]
Hello there! I'm still getting this crash with version 2.11.8 of Double Slabs and 0.8.1 of Block Carpentry

Report: https://paste.ee/p/tBH73
