### ISSUE TITLE
Crash with vertical slabs on Create contraption 

### ISSUE THREAD

**Issue by rwallac** [CJMinecraft01/DoubleSlabs#114]
I found this crash while playing Valhelsia Origins, I had a vertical slab on a Crate contraption, as soon as I activated it, my game crashed, and every time I log into the server or another player goes near by, we are crashed out 

[crash-2020-09-05_22.03.02-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5178991/crash-2020-09-05_22.03.02-client.txt)

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version :) Sorry for the delay
