### ISSUE TITLE
[crash] [1.15.2] crash when initialising game.

### ISSUE THREAD

**Issue by Bass2style** [CJMinecraft01/DoubleSlabs#117]
Hi,

my game is crashing when loading a modpack with the actual latest update of the mod.

forge version : 31.2.36
mod version : DoubleSlabs-1.15-2.11.1

crashlog :
https://pastebin.com/ui02rj8Z
https://pastebin.com/nb2TwD37

have a nice day.

**Comment by Bass2style** [comment]
Hi,

it's still crashing with 2.11.2 version, it seems identical than the two others, but here is the crashlog : https://pastebin.com/E5eCQj1h

idk if it's impacting, but here is my modlist, if that can help : https://pastebin.com/7vb90iQb

edit : 
i've tryed with only JEI/ToP/JourneyMap/MaEssentials + DoubleSlabs, and it's running correctly, so, another mod seems conflicting.
edit 2 : 
crashlogs talks about Immersive Portals, i've tryed the same setup as above, with MixinsBootstrap and ImmersivePortals, but seems not crashing either, so it's coming from something else.

**Comment by CJMinecraft01** [comment]
Do you have a modpack link so I can download and test it more easily please?

**Comment by Bass2style** [comment]
it's a custom pack, but i can create an instance with my launcher. i'm doing this now. 

edit : posted it on my Mega, but i can share it elsewhere if needed : https://mega.nz/file/ylhVRQAL#Wwvdr1_HoDhWjm1UTLCR_ZlWs4ekZNtmZ5BMnG757cU

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version :)

**Comment by Bass2style** [comment]
my pack is running with the last version, thanks for the support.
