### ISSUE TITLE
[1.15.2] double bug with vertical slabs.

### ISSUE THREAD

**Issue by Bass2style** [CJMinecraft01/DoubleSlabs#121]
Hi,

i actually found two bugs with the vertical slabs,

the first one is that you can't mine vertical slabs back, when you break it, it's disappearing. (you get some back in some strange conditions.

the second one, is that when you craft a vertical slab, and place it, you can place it in an infinite amount when placed on a wall. (but it's used when placed on the floor)

i recorded those behaviors, you can find a vidéo here : https://youtu.be/D_5VD3l8JV4

**Comment by CJMinecraft01** [comment]
Hi! Thanks for reporting this. I have discovered how to fix the issues and will post a new version as soon as possible :)

**Comment by Bass2style** [comment]
Hi,

great and quick support, trying the update when i have a bit of time.

thanks for support.
