### ISSUE TITLE
Weird crash on autobreaking of a slab

### ISSUE THREAD

**Issue by gerb82** [CJMinecraft01/DoubleSlabs#123]
Whenever i try to break a vertical slab with an engineer's decor small block breaker, the game dies

double slabs - 2.11.5
forge - 31.2.36
engineer's decor - 1.1.2
mc - 1.15.2
modpack - valhesia 2.2.8a with a few extra unrelated mods

crash log:
[crash-2020-09-15_21.59.54-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5227198/crash-2020-09-15_21.59.54-server.txt)

totally didn't find this one on accident while looking for another bug

**Comment by CJMinecraft01** [comment]
Fixed in the latest version :)
