### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by inconnu2000** [CJMinecraft01/DoubleSlabs#126]
[https://imgur.com/a/KTlfXwM](url)

I tested this on the latest forge update and without any other mod on 1.16.2

**Comment by CJMinecraft01** [comment]
Hi, thanks for the report. The link doesn't seem to be working :)

**Comment by inconnu2000** [comment]
![bug double slab](https://user-images.githubusercontent.com/57439253/93540477-11d59300-f954-11ea-97b3-d08f5f34d0c2.gif)
Hope this will work this time :)

**Comment by CJMinecraft01** [comment]
Are you on the latest version as I thought I had fixed this issue? (I had spotted it myself just after release)

**Comment by inconnu2000** [comment]
![Capture d’écran 2020-09-18 150835](https://user-images.githubusercontent.com/57439253/93601089-ee94fd00-f9c0-11ea-9c16-2575a7653890.png)
it's the latest for 1.16.2

**Comment by CJMinecraft01** [comment]
Fixed in the latest version :) Sorry about that :)
