### ISSUE TITLE
Juts placed a vertical slab and it crashed

### ISSUE THREAD

**Issue by KenyMylankca** [CJMinecraft01/DoubleSlabs#127]
[crash-2020-09-18_17.40.09-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246156/crash-2020-09-18_17.40.09-server.txt)

**Comment by CJMinecraft01** [comment]
Do you have a link to the modpack you are playing on so I can see if I can recreate this issue?

**Comment by KenyMylankca** [comment]
[crash-2020-09-18_17.55.40-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246240/crash-2020-09-18_17.55.40-client.txt)
and here's another crash that says it crashes with snow real magic mod
yes i do have a [modpack](https://github.com/KenyMylankca/kenijeys-modpack) that i'm working on for years

**Comment by KenyMylankca** [comment]
and the place i placed thr vertical slab was snowy.

**Comment by CJMinecraft01** [comment]
Thanks, I'll take a look and see what I can do :)

**Comment by KenyMylankca** [comment]
thank you too

**Comment by KenyMylankca** [comment]
and here's a few more crash reports i just got. i placed vertical slabs on sand(beach) and bla bla
and last time it crashed when i place regular slab(oak wood planks)
[crash-2020-09-18_18.03.09-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246314/crash-2020-09-18_18.03.09-server.txt)
[crash-2020-09-18_18.03.08-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246315/crash-2020-09-18_18.03.08-server.txt)
[crash-2020-09-18_18.03.07-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246316/crash-2020-09-18_18.03.07-server.txt)
[crash-2020-09-18_18.03.06-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246317/crash-2020-09-18_18.03.06-server.txt)
[crash-2020-09-18_18.03.05-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246318/crash-2020-09-18_18.03.05-server.txt)
[crash-2020-09-18_18.03.04-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246319/crash-2020-09-18_18.03.04-server.txt)
[crash-2020-09-18_18.03.03-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246320/crash-2020-09-18_18.03.03-server.txt)
[crash-2020-09-18_18.03.14-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246321/crash-2020-09-18_18.03.14-server.txt)
[crash-2020-09-18_18.03.13-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246322/crash-2020-09-18_18.03.13-server.txt)
[crash-2020-09-18_18.03.12-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246323/crash-2020-09-18_18.03.12-server.txt)
[crash-2020-09-18_18.03.11-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246324/crash-2020-09-18_18.03.11-server.txt)
[crash-2020-09-18_18.03.10-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5246325/crash-2020-09-18_18.03.10-server.txt)

**Comment by TacoLite** [comment]
I've also experienced a crash similar to this on a beach, with the snow real magic mod and the quark mod installed. I attempted to place a vertical slab onto sand covered snow and the game immediately crashed.

Here's a pastebin: https://pastebin.com/fYZmrq3c

**Comment by KenyMylankca** [comment]
yeah PLEASE fix this asap... thanks!

**Comment by CJMinecraft01** [comment]
I am sincerely sorry for the delayed response but I believe that this is fixed in the latest version. Thank you for your patience
