### ISSUE TITLE
Compat w/ Windowlogging Mod

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#128]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Double Slabs v2.11.7`
[`Windowlogging v0.0.1`](https://www.curseforge.com/minecraft/mc-mods/windowlogging)

If I add the `doubleslabs:vertical_slab` to the `windowlogging:windowable` tag, I will be able to combine a glass pane with the vertical slabs, but the vertical slab will then have a missing texture. If I then break the glass pane, the vertical slab changes to an Air Vertical Slab, which can crash the game. Is proper compatibility possible?
[Crash Report](https://gist.github.com/WenXin20/aeaa85d3f2760fc4c836a7a226e524de)

Also reported here, since I wasn't sure where it was best to have this addressed: 
LordGrimmauld/windowlogging#1

**Comment by LordGrimmauld** [comment]
I fixed the nbt resetting (will be released soon), the rendering will need a rework on both sides. I will try to get it working and open a PR to this mod when done.

**Comment by LordGrimmauld** [comment]
Correction: this works without any modifications to double slabs mod, therefore i believe the issue on this issue tracker is closeable.
Tested: 0.0.2 windowlogging, which i am working on right now.

**Comment by WenXin20** [comment]
Alright, thanks!
