### ISSUE TITLE
Server crash (1.12.2)

### ISSUE THREAD

**Issue by CalaMariGold** [CJMinecraft01/DoubleSlabs#130]
[crash-2020-09-19_16.52.11-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5250590/crash-2020-09-19_16.52.11-server.txt)
[latest.log](https://github.com/CJMinecraft01/DoubleSlabs/files/5250591/latest.log)

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for reporting this and apologies for the delay, this should now be fixed in the latest version. Thank you for your patience :)
