### ISSUE TITLE
Raised campfire doesn't display with Hwyla

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#131]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Double Slabs v2.11.7`

The raised campfire doesn't show any information with Hwyla, and the double vertical campfire in Hwyla says the block is vertical air. Just a minor bug.

**Comment by WenXin20** [comment]
I've just noticed that the raised campfire doesn't drop when mined and doesn't damage the player when doubled.
Breaking animation is in the wrong spot (similar to my other report).
It also has a culling issue when it's facing north/east and placed vertically.

**Comment by WenXin20** [comment]
With the mod [Extended Nether Backport](https://www.curseforge.com/minecraft/mc-mods/extended-nether-backport), the Soul Campfire can be doubled, but the top is orange instead of blue.

**Comment by CJMinecraft01** [comment]
Hi there! Thank you for reporting this, I've managed to fix the first issue with dropping the appropriate item, the breaking animation and culling issue. I will try to fix the other issue when I backport the new version to 1.15. Thank you for your patience

**Comment by WenXin20** [comment]
Of course! Take all the time you need. I'm using 1.16.5 now anyways.

**Comment by CJMinecraft01** [comment]
Just a quick update, I've added the support for the soul campfire for the 1.15 version. Thanks again for your patience
