### ISSUE TITLE
Visual Bug [1.15.2]

### ISSUE THREAD

**Issue by dimasasus** [CJMinecraft01/DoubleSlabs#132]
When placing 2 different double vertical slabs near other vertical slabs some of the textures don't render properly. This only happens when two different slabs are placed together in one block and only affects textures of the slab that has been placed  first. Horizontal slabs don't have/cause this issue. I do use optifine, however disabling it or changing any options doesn't solve the problem.
![2020-09-20_21 01 09](https://user-images.githubusercontent.com/62846740/93718496-61e76c00-fb85-11ea-9c60-2e68816ddb5d.png)
![2020-09-20_21 00 56](https://user-images.githubusercontent.com/62846740/93718498-6449c600-fb85-11ea-9e29-b56c6e97da06.png)
![2020-09-20_21 01 00](https://user-images.githubusercontent.com/62846740/93718500-66ac2000-fb85-11ea-89a2-3c7723aa8110.png)
![2020-09-20_21 01 05](https://user-images.githubusercontent.com/62846740/93718501-6744b680-fb85-11ea-8f61-780f69621cb0.png)

**Comment by CJMinecraft01** [comment]
Hi, thanks for the report! I've tried to reproduce this myself and can't seem to do so. Have you tried reloading the textures?

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extremely delayed response. This is now fixed in the latest version :)
