### ISSUE TITLE
LOTR needs updated compat

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#134]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Double Slabs v2.11.8`
[`Lord of the Rings Renewed v2.1.2`](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed)

The mod just had an update that rewrote their vertical slab placements, so now whenever I try to place a lotr slab vertically, this happens everytime:

![2020-09-21_12 49 55](https://user-images.githubusercontent.com/12000593/93802871-a1579c00-fc09-11ea-8f82-7d2cb522c74b.png)

**Comment by CJMinecraft01** [comment]
Apologies for the delay, this should now be fixed in the latest version :)
