### ISSUE TITLE
Vertical Slabs from other mods can't be doubled

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#135]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Double Slabs v2.11.8`

I cannot combine two vertical slabs, such as from quark or other mods, together to make a double slab. A normal horizontal slab has to be used to convert the quark vertical slab into a double slab block. 

Also, if a quark vertical slab is converted into a double slab block, the break animation is off.

![2020-09-21_13 11 16](https://user-images.githubusercontent.com/12000593/93804498-feece800-fc0b-11ea-904d-b8e0b3afc563.png)

**Comment by WenXin20** [comment]
The mod Bamboo Blocks is also missing compat for it's vertical slabs.

**Comment by CJMinecraft01** [comment]
Thanks for the report and apologies for the delay, this is finally fixed in the latest version I believe :)
