### ISSUE TITLE
[1.15.2] DoubleSlabs is triggering the creation of infinite threads + instances of ServerWorld.

### ISSUE THREAD

**Issue by Vaelzan** [CJMinecraft01/DoubleSlabs#137]
DoubleSlabs 1.15.2-2.11.7 (didn't see any relevant changes in 2.11.8 that would render this report invalid though)
Forge 31.2.41

BlockInfo's setWorld is creating a new ServerWorldWrapper (with new threads) every time it is called. This happens over and over again until the server crashes, in the example below after creating about ten thousand threads.

Crash Report:
https://gist.github.com/Vaelzan/72bd4637b15df5fb37da71f0aadca0c8

Immediately after this, there is another crash report that is several megabytes in size, showing just how many threads have been created. There are thousands all like this (snippet of the report to avoid having to paste literally 100,000 lines):
https://gist.github.com/Vaelzan/17c64b6fb6b0225c67302ea687086319

**Comment by Won-Ton** [comment]
This mod creates a [new ServerWorld](https://github.com/CJMinecraft01/DoubleSlabs/blob/e908bfffb0e6680d61f7ad86364565c5da901812/src/main/java/cjminecraft/doubleslabs/api/BlockInfo.java#L108) and all the resources that go along with it for every vertical slab that gets placed. [Twice...](https://github.com/CJMinecraft01/DoubleSlabs/blob/1.15.x/src/main/java/cjminecraft/doubleslabs/common/tileentity/SlabTileEntity.java#L107-L108)
This is problematic for a lot of reasons.

I'd suggest finding another way to solve the problem that the WorldWrappers were made to address.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response.. This should be fixed in the latest version and you should hopefully see that your performance is better! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :) Thanks again for reporting this and apologies for the delay
