### ISSUE TITLE
Phantom Vertical Slabs Causing Game to Crash

### ISSUE THREAD

**Issue by TrueDakkon** [CJMinecraft01/DoubleSlabs#138]
When placing vertical slabs in a creative world and then breaking them I noticed that the game kept freaking out and bringing back slabs I had just broken or was showing the collision box for a slab that wasn't there. It would even go so far as to override slabs with those that had been placed in the location prior. Continuing to try and place and break slabs eventually resulted in my game crashing.
[Crash Report](https://pastebin.com/8cf8RdGH)

**Comment by ashton727** [comment]
Had a similar issue

**Comment by CJMinecraft01** [comment]
Thanks for the report and my sincerest apologies for the delayed reply. This is now fixed in the latest version.
