### ISSUE TITLE
Crash the game

### ISSUE THREAD

**Issue by SoyJetixXD** [CJMinecraft01/DoubleSlabs#14]
Information: Hello, download your mod because I find it interesting so I added it to my modpack, I just try it, all correct, but when I break the block my game crashes. 
![Captura de pantalla (5)](https://user-images.githubusercontent.com/60457424/77021405-93704800-6954-11ea-8b1e-ca5170cf6985.png)
Link:https://paste.dimdev.org/utudozifoy.mccrash

**Comment by CJMinecraft01** [comment]
Thanks for the bug report. I have an idea of what this possibly may be and I'll get round to fixing it as soon as possible

**Comment by CJMinecraft01** [comment]
Fixed in the latest version
