### ISSUE TITLE
Registry Crash

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#141]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Double Slabs v2.11.8`
[`Vanilla Magic v2.0.2`](https://www.curseforge.com/minecraft/mc-mods/vanilla-magic)

Most of the time when trying to launch the game, my game crashes after less than a minute of loading. Seems to happen more if vanilla magic is installed?
[Crash Report](https://gist.github.com/WenXin20/dd7eae4e1719485109908645f9bb9290)

**Comment by Sejoslaw** [comment]
Seems like DSBlocks.DOUBLE_SLAB.get() returns null.

https://github.com/CJMinecraft01/DoubleSlabs/blob/1.15.x/src/main/java/cjminecraft/doubleslabs/client/proxy/ClientProxy.java#L96

**Comment by CJMinecraft01** [comment]
Apologies for the delay, this is now fixed in the latest version :)
