### ISSUE TITLE
DoubleSlabs crashes my modpack when its installed.

### ISSUE THREAD

**Issue by Tim-Rambo** [CJMinecraft01/DoubleSlabs#142]
https://pastebin.com/7GyrmbNG

Lemme know asap for what extra info ya need thanks

Kind Regards
TimRambo

**Comment by CJMinecraft01** [comment]
Hi, sorry, the pastebin link doesn't seem to be working..

**Comment by Tim-Rambo** [comment]
> Hi, sorry, the pastebin link doesn't seem to be working..

oh, i forgot to change the option on pastebin i made it destroy itself after 1hour ups.
here is a new one and it wont destroy itself 👍 
https://pastebin.com/0ExkgFZh

**Comment by Tim-Rambo** [comment]
Hello have you checked my log?
Ive updated the pastebin now 👍

**Comment by Vaelzan** [comment]
Have you tried using Forge 28.2.23 instead of 28.2.0? The one you have is pretty ancient, even by 1.14.4 modding standards. I know it's what Forge has marked as recommended, but most mods work better on the newer builds.

**Comment by Tim-Rambo** [comment]
> Have you tried using Forge 28.2.23 instead of 28.2.0? The one you have is pretty ancient, even by 1.14.4 modding standards. I know it's what Forge has marked as recommended, but most mods work better on the newer builds.

Ive forgotten to check out DS on that forge bcs i updated my pack to that bcs thats where optifine and optiforge works thanks for the idea :D

**Comment by Tim-Rambo** [comment]
It worked now bcs i am on latest forge version. Thanks for the response.
