### ISSUE TITLE
Client crash after destroying vertical stone brick slab

### ISSUE THREAD

**Issue by Communos** [CJMinecraft01/DoubleSlabs#143]
As stated in the title, the game crashed after breaking a vertical stone brick slab. Wasn't the first time this happened while playing on a server. Game Version is 1.16.2 , mod version is "DoubleSlabs-1.16-3.4.10"
[crash-2020-10-11_16.17.41-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5361258/crash-2020-10-11_16.17.41-client.txt)

**Comment by ashton727** [comment]
I saw you have KleeSlabs in your mods, DoubleSlabs already has this feature, and could be the problem

**Comment by Communos** [comment]
Didn't know DoubleSlabs also has this feature. Thanks for letting me know.
