### ISSUE TITLE
raised campfire/soul campfire causing crash

### ISSUE THREAD

**Issue by wcsorrow** [CJMinecraft01/DoubleSlabs#145]
I've tried solving on my own, but I don't understand how blacklisting works or if that would even help in this case. double slabs worked fine when we first started the server two days ago, but now i cant even connect to the other players server because of a registry sync failure being caused by those raised campfires/soul campfires. we tried older and newer versions of doubleslabs, but im honestly not sure whats going onI linked the debug below, thanks for any help you can provide.

[debug.log](https://github.com/CJMinecraft01/DoubleSlabs/files/5368137/debug.log)

**Comment by CJMinecraft01** [comment]
Thank you for the bug report. Firstly may I apologise in the delayed response. I'm not too sure about what is causing this issue but will take a look as soon as I can. Thank you for your patience.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay, can I check that double slabs was also installed on the server please?
