### ISSUE TITLE
Mod seems to cause a ticking entity error

### ISSUE THREAD

**Issue by PutridNonsense** [CJMinecraft01/DoubleSlabs#148]
MC Version: 1.12.2
Forge Version: 14.23.5.2854
Mod Version: 0.11.0

This is the error that comes up when it crashes: https://i.imgur.com/TGQWtA3.png

And this is the error log: https://gist.github.com/CLMagnus/f5f481f6f1f38e3b64d6f57fb07d2358

It only crashes like this if you place down a vertical slab. Haven't tested with normal slabs from this mod yet

**Comment by CJMinecraft01** [comment]
Thank you for the bug report. Firstly may I apologise for the delayed response. I believe the issue you are facing is a duplicate of #140 (although a different dimension id). Please refer to that issue thread, thank you :)
