### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by Tim-Rambo** [CJMinecraft01/DoubleSlabs#149]
Forge: Latest
Modpack: My Own
Mod Version: DoubleSlabs-1.12-0.11.0.jar
Using: https://magmafoundation.org 
Magma Version:  Magma version 12a54a3 and i tried the v3a65e28 of magma 

but the mod crashes on either 1

Just disabled doubleslabs and my server just launched and started just fine.

Magma V12
https://pastebin.com/7iHBZ0rG

Magma V3
https://pastebin.com/2FQMmb0n

**Comment by BluEagle-Dev** [comment]
i have the same problem

**Comment by Ayfri** [comment]
Same.

**Comment by xemnes** [comment]
same with mohist

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay, this is now fixed in the latest version. Thank you for your patience :)
