### ISSUE TITLE
1.16.3 shaders issue

### ISSUE THREAD

**Issue by SwordsAndSandals** [CJMinecraft01/DoubleSlabs#150]
i dont know why, but Shaders put "missing textures"(the purple and black squares) on mixed slabs at times. Have tried multiple shaders, but sometimes restarting the whole game fixes it.
![2020-10-25_14 52 06](https://user-images.githubusercontent.com/73429133/97107764-e885f080-16d1-11eb-943c-fc1d0f5dac6a.png)

**Comment by enduum** [comment]
Same issue. Only happens with horizontal mixed slabs when shaderpack is enabled
![2020-11-02_13 34 23](https://user-images.githubusercontent.com/73849784/97905840-b21f2580-1d10-11eb-975c-0f77cd97b2d6.png)

**Comment by CJMinecraft01** [comment]
Thank you for the bug report and sorry for the delay in response. Does this happen specifically on 1.16.3 or is this a general issue?

**Comment by enduum** [comment]
It happens on 1.16.4 as well. It only happens when enabling or disabling shaderpacks and it only lasts until I relaunch the game. After restarting, the issue doesn't reappear unless I enable/disable shaderpacks again. Swapping between shaderpacks doesn't incur any issue.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response, would you mind testing this in the latest version please? I believe that this should be fixed :)
