### ISSUE TITLE
Crash w/ Improved Stations

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#151]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Double Slabs v2.11.8`
[`Improved Stations v1.3`](https://www.curseforge.com/minecraft/mc-mods/improved-stations-forge)

I got this crash after trying to combine 2 crafting station slabs together.
[Crash Report](https://gist.github.com/WenXin20/e550d0d3b7c8e1672433311988c11e15)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extreme delay, but I have finally fixed this in the latest version :)
