### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by Altodeso** [CJMinecraft01/DoubleSlabs#152]
it crash
[hs_err_pid5444.log](https://github.com/CJMinecraft01/DoubleSlabs/files/5467258/hs_err_pid5444.log)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response. There log you have posted is a JVM crash log and is not directly associated with my mod. Would you mind explaining what happened before crashing and if there is a crash log, can you show it please? (It's in the crash-logs folder)

**Comment by Altodeso** [comment]
i dont remember what happened it was too long ago and lost all the crash logs when i change from pc

**Comment by CJMinecraft01** [comment]
Okay, no worries :) Thanks again for reporting this, I can't see anything specific that I can fix here so I will close this. If you have any other issues, please be sure to report them :)
