### ISSUE TITLE
Automatically place a vertical slab on the side of blocks instead of the default horizontal slab.

### ISSUE THREAD

**Issue by PhantomH17** [CJMinecraft01/DoubleSlabs#153]
I've used this mod for quite some time already. Initially everything works just fine, you can place slab like normal and when you hold shift you can place the slab vertically. However, after some time (or maybe some update?) suddenly the default slab placement is vertical. If you want to place the slab normally (horizontal), you have to press shift. Fortunately for me, there is no other problem that emerge from this sudden oddity other than this mod becomes quite unwieldy. Could you please fix this issue?  Thanks!

**Comment by CJMinecraft01** [comment]
Thank you for the report and sorry for the delay in response. There was a change in the default placement mechanism which is used in an attempt to be more intuitive. You can change this though in the client config to the original placement mechanism. Hope that helps :)
