### ISSUE TITLE
Minecraft Double Slabs Electroblob's Wizardry Crash

### ISSUE THREAD

**Issue by TheidenHD** [CJMinecraft01/DoubleSlabs#158]
Crashes on startup when Electroblob's Wizardry 4.3.x is installed
https://pastebin.com/czDFkPkH
https://github.com/Electroblob77/Wizardry/issues/542

**Comment by Ayfri** [comment]
Same !

**Comment by TheidenHD** [comment]
Ok everything i figured out so far:
cjminecraft.doubleslabs.client.ClientConstants.getFallbackModel
is only called on startup when Wizardry is installed.

Minecraft.getMinecraft().getBlockRendererDispatcher() 
returns null wen it is called on startup.

Minecraft.blockRenderDispatcher
is only initialized after the Minecraft.run method is called

**Comment by TheidenHD** [comment]
https://github.com/TheidenHD/DoubleSlabs/releases/tag/0.11.1

**Comment by CJMinecraft01** [comment]
Thanks for reporting this, it appears that this has now been fixed :)
