### ISSUE TITLE
0.11.0 crashes dedicated server Forge 1.12.2 build 2854

### ISSUE THREAD

**Issue by kreezxil** [CJMinecraft01/DoubleSlabs#161]
Notes:
     invalid side SERVER

crash report: 
https://gist.github.com/5dac13403b10ff85f701fa87bbcaa7d4

fml server latest: 
https://gist.github.com/4d2a634696ac22a64fd98be1f9c013cd

**Comment by TheTedder** [comment]
I'm getting the same error. Here it is even with foamfix's coremod disabled. https://pastebin.com/MRFm7rUx

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay, this is now fixed in the latest version. Thank you for your patience :)
