### ISSUE TITLE
Gamecrash after teleport --> Rendering Block Entity

### ISSUE THREAD

**Issue by zwibblTV** [CJMinecraft01/DoubleSlabs#163]
Im using DoubleSlabs v3.4.10 in a modpack with other mods (listed [here](https://www.technicpack.net/modpack/drugar-10.1734791))
Today, my game crashed several times after teleporting (with the portable teleporter from mekanism) back home. I have no problemes without Optifine yet.
My crashlog: [crash-2020-12-18_18.04.52-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5717433/crash-2020-12-18_18.04.52-client.txt)

**Comment by CJMinecraft01** [comment]
Apologies for the delayed response.. this is should be fixed in the latest version!
