### ISSUE TITLE
Abnormals vertical slabs have odd texture rotation

### ISSUE THREAD

**Issue by solarsonata** [CJMinecraft01/DoubleSlabs#164]
![image](https://user-images.githubusercontent.com/24257045/102688102-50e1e180-41ec-11eb-8ec5-1a4b6dc5add2.png)
(To be clear, this is the vertical slab generated by this mod, not the separate block added by Upgrade Aquatic)

**Comment by CJMinecraft01** [comment]
Thank you for the report and sorry for the delayed response. Please try adding the block name to the lazyVerticalSlabModels list in the client config file and this issue should be resolved :)

**Comment by solarsonata** [comment]
Ah, thanks
