### ISSUE TITLE
When placed on another vertical slab, ender campfire becomes soul campfire

### ISSUE THREAD

**Issue by solarsonata** [CJMinecraft01/DoubleSlabs#165]
https://user-images.githubusercontent.com/24257045/102688184-dd8c9f80-41ec-11eb-8e7c-7eccbb7ab339.mp4

**Comment by CJMinecraft01** [comment]
Thank you for the bug report and sorry for the delayed response. What mod is the ender campfire from please?

**Comment by solarsonata** [comment]
It's from Endergetic Expansion. No worries about the response time, there's 41 issues after all!

**Comment by CJMinecraft01** [comment]
My sincerest apologies for the delay in fixing this, but this should finally be fixed in the latest version :)
