### ISSUE TITLE
Cryptic Campfire Server Crash

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#167]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Double Slabs v3.4.10`

If the Cryptic and Green Campfires from Biomes You'll Go and placed as a double slab, it becomes a Soul Campfire. Then I got a server crash when I broke the campfire while it was cooking Assorted Seeds from the Terraqueous mod.
[Crash Report](https://gist.github.com/WenXin20/45802e33616f3aa2a7ca4bfd6d6389d1)

**Comment by CJMinecraft01** [comment]
Hi there! Sorry for the delay in fixing this, I believe this is now fixed in the latest version :)
