### ISSUE TITLE
Double Feeding Slab Error w/ Productive Bees

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#168]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Productive Bees v0.5.2.1`
`Double Slabs v3.4.10`

When a Feeding Slab is made into a double slab with the Productive Bees mod installed, the gui won't open and instead prints an error. 
[Error Log](https://gist.github.com/WenXin20/1855b1d51e8e1cf73caa4c6412934aad)

**Comment by CJMinecraft01** [comment]
Sorry for the delayed response... I've finally fixed this in the latest version!

**Comment by WenXin20** [comment]
Thanks! No worries.
