### ISSUE TITLE
Purple and black blocks 

### ISSUE THREAD

**Issue by Benedictct** [CJMinecraft01/DoubleSlabs#169]
Hello, usually the slabs work fine, but sometimes they turn into black and purple checkered blocks. Can I fix this?

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response, which mod version and Minecraft version are you using? Also, are any errors shown in the console log? Thanks :)

**Comment by Benedictct** [comment]
Hello, 
I was using the 1.16.3 version I think and playing in that minecraft version too? 
Should I try to use the 1.17 version now?

**Comment by CJMinecraft01** [comment]
There is currently no 1.17 version but if you would try the latest version for 1.16.5 that would be fantastic :)
