### ISSUE TITLE
Compat w/ Assorted Decor

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#172]
[Assorted Decor](https://www.curseforge.com/minecraft/mc-mods/assorted-decor) adds a Colorizer Slab, which can be textured with any block using the Colorizer Brush, but this doesn't work with Double or Vertical Slabs.

**Comment by CJMinecraft01** [comment]
Thank you again for reporting this, I've added support in the latest version! Apologies for the delay..
