### ISSUE TITLE
1.12.2 Could not get provider type for dimension 6, does not exist 

### ISSUE THREAD

**Issue by ghost** [CJMinecraft01/DoubleSlabs#173]
Hi,

So i'm currently making a Modpack and used your Mod in it. 

While it worked completely fine at the start, it suddenly crashed after placing an ebony slab from forestry as a vertical slab and the log showed **Could not get provider type for dimension 6, does not exist**

And i started researching about that error: usually it happens, when there are two mods with Dimensions that have the same Id-Number. 

So i searched in my config files and the only dimension i have, aside from -1,0 and 1 is the ID 7 from Twilight forest.

Thats why i dont really know what to do, i dont have any dimension with the ID of 6 so it shouldnt even give out this error but when i deactivated your mod it launched without any problem, until i activated it and placed a vertical slab again.

Hope you can help me, i really like this mod and dont want to kick it out of my modpack.

Here's my log and my Modpack including my save and all my configs, which is still in its early stages... didnt want to post it but i think you can't help without it.

[crash-2021-01-05_16.57.40-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5771286/crash-2021-01-05_16.57.40-server.txt)

https://drive.google.com/file/d/1z5M6w-Vv3Z8J3bxO5zNTGNKX7-y-oISa/view?usp=sharing

**Comment by CJMinecraft01** [comment]
Hi there! Thank you for reporting this and apologies for the delay, this is now fixed in the latest version. Thank you for your patience
