### ISSUE TITLE
Server crush caused by DoubleSlabs 1.12.2

### ISSUE THREAD

**Issue by NerelTeC** [CJMinecraft01/DoubleSlabs#179]
[crash-2021-02-14_14.48.25-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/5977662/crash-2021-02-14_14.48.25-server.txt)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay, this is now fixed in the latest version. Thank you for your patience
