### ISSUE TITLE
Placement Lag (1.12.2@F2847)

### ISSUE THREAD

**Issue by KenyMylankca** [CJMinecraft01/DoubleSlabs#18]
It lags (game freezes) like 1 second or bit less when i place a double slab. it happens in my modpack so dunno how it goes in other situations. can u fix this please. thanks.
my modpack: https://www.technicpack.net/modpack/kenijeys-modpack.1441336

**Comment by CJMinecraft01** [comment]
Do you happen to have Dynamic Surroundings installed?

**Comment by KenyMylankca** [comment]
what????????

**Comment by CJMinecraft01** [comment]
In the modpack you were using and were experiencing placement lag, did you have the Dynamic Surroundings mod installed? I think there may be a compatibility issue between my mod and theirs

**Comment by KenyMylankca** [comment]
yes i had dynamic surroundings.

**Comment by pimalel233** [comment]
I confirm that removing Dynamic Surroundings from my test pack solved the placement lag - Current mod list: https://pastebin.com/ym0uDDZ7

**Comment by Pulz-TCP** [comment]
Jumping on this issue to confirm the same problem, and as the last few comments suggested- I do have Dynamic Surroundings. Is that a problem you'd be able to fix @CJMinecraft01 or would it be better to open an issue on their side?

Here is a crash log provided by a user, vanillafix threw them to the menu and provided it:
https://paste.dimdev.org/izuvetosic.mccrash

Thanks

**Comment by CJMinecraft01** [comment]
I am currently working on a fix for this but unfortunately I won't be able to include this into DoubleSlabs itself as it uses classes from DS. I will have to make a PR on DynamicSurroundings to try and fix this as this is a behaviour that is due to the type of blockstate I'm using meaning this issue may occur with other mods as well

**Comment by CJMinecraft01** [comment]
Thanks for the help in confirming that this issue was to do with Dynamic Surroundings. I've managed to create a patch within double slabs which means in the latest version the placement lag should be eradicated! Let me know if you have any further issues!

**Comment by Pulz-TCP** [comment]
Thanks for the speedy response @CJMinecraft01, but after updating from 0.2.1 to that new 0.3.0 build I get a crash!
Edit; Not a crash, but the server hangs.
https://gist.github.com/PulzHF/ad3e488ff0071627578c9b437dd2b701

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!

**Comment by CJMinecraft01** [comment]
Let me know if everything is working okay and then I can close this issue :)

**Comment by Pulz-TCP** [comment]
> Let me know if everything is working okay and then I can close this issue :)

Looking into it now

**Comment by Pulz-TCP** [comment]
@CJMinecraft01 The crash is gone, and I can't seem to replicate the lag issue

**Comment by CJMinecraft01** [comment]
Fantastic! Thanks for all the help testing this!

**Comment by KenyMylankca** [comment]
i will debug into it also and will give info to here if i find any issues

**Comment by CJMinecraft01** [comment]
Sweet. Keep me posted!
