### ISSUE TITLE
[1.16.5] Ticking block crash. Soul Campfire on hopper.

### ISSUE THREAD

**Issue by Helloua4** [CJMinecraft01/DoubleSlabs#181]
Placing a Soul Campfire on a hopper made my solo game crash, and wouldn't let me back in.
I have 52 mods installed but the crash report indicated a problem with this mod specifically. (see report below)
The game crashed as soon as I place the campfire, and the coordinates in the report confirm it to be the cause of the ticking block.

Fortunately, deleting the mod altogether resolved the ticking block.
No harm done: I only had about 9 vertical slabs that got deleted with it (I didn't combine any slabs because it seemed to cause texture problems once I had a shader installed...)

---- Minecraft Crash Report ----
// You're mean.

Time: 4/19/21 7:58 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{doubleslabs:vertical_slab}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.tileentity.CampfireTileEntity.func_73660_a(SourceFile:42) ~[?:?] {re:classloading}
	at cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_73660_a(SlabTileEntity.java:189) ~[?:3.5.0rc1] {re:mixin,re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6826/295621064.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.tileentity.CampfireTileEntity.func_73660_a(SourceFile:42) ~[?:?] {re:classloading}
	at cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_73660_a(SlabTileEntity.java:189) ~[?:3.5.0rc1] {re:mixin,re:classloading}
-- Block entity being ticked --
Details:
	Name: doubleslabs:dynamic_slab // cjminecraft.doubleslabs.common.tileentity.SlabTileEntity
	Block: Block{doubleslabs:vertical_slab}[double=false,facing=north,waterlogged=false]
	Block location: World: (-138,30,-297), Chunk: (at 6,1,7 in -9,-19; contains blocks -144,0,-304 to -129,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{doubleslabs:vertical_slab}[double=false,facing=north,waterlogged=false]
	Block location: World: (-138,30,-297), Chunk: (at 6,1,7 in -9,-19; contains blocks -144,0,-304 to -129,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['helloua'/229, l='ServerLevel[2021]', x=-136.96, y=30.00, z=-293.56]]
	Chunk stats: ServerChunkCache: 7569
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,72,-256), Chunk: (at 0,4,0 in -9,-16; contains blocks -144,0,-256 to -129,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2830359 game time, 3831759 day time
	Level name: 2021
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 55578 (now: false), thunder time: 160527 (now: false)
	Known server brands: vanilla, forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6826/295621064.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1920192144 bytes (1831 MB) / 4186963968 bytes (3993 MB) up to 4186963968 bytes (3993 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		enchantedbookredesign-3.3-1.16.4.jar              |Enchanted Book Redesign       |enchantedbookredesign         |3.3-1.16.4          |DONE      |NOSIGNATURE
		vanillaextension-1.16.5-1.0.16.jar                |Vanilla Extension             |vanillaextension              |1.16.5-1.0.16       |DONE      |NOSIGNATURE
		supermartijn642configlib-1.0.5a-mc1.16.jar        |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.5a              |DONE      |NOSIGNATURE
		preciseblockplacing-1.0.6+1.16.5.jar              |Precise Block Placing         |preciseblockplacing           |1.0.6               |DONE      |NOSIGNATURE
		torchslabmod-1.16.4_v1.6.18.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.4.88.jar                           |Just Enough Items             |jei                           |7.6.4.88            |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		goldenhopper-1.1.1-1.16.3.jar                     |Golden Hopper                 |goldenhopper                  |1.1.1               |DONE      |NOSIGNATURE
		easyelytratakeoff_1.16.5-1.7.jar                  |Easy Elytra Takeoff           |easyelytratakeoff             |1.7                 |DONE      |NOSIGNATURE
		Clumps-6.0.0.21.jar                               |Clumps                        |clumps                        |6.0.0.21            |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		Controlling-7.0.0.14.jar                          |Controlling                   |controlling                   |7.0.0.14            |DONE      |NOSIGNATURE
		jumpoverfences-1.16.4-1.0.1.jar                   |Jump Over Fences              |jumpoverfences                |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		torchoptimizer-1.16.5-2.4.8.jar                   |Torch Optimizer               |torchoptimizer                |2.4.8               |DONE      |NOSIGNATURE
		advancedtools-1.16.5-1.0.2.jar                    |Advanced Tools                |advancedtools                 |1.16.5-1.0.2        |DONE      |NOSIGNATURE
		Batty's Coordinates PLUS Mod for Forge-1.16.4-0.1.|Batty's Coordinates Plus Mod f|coordinatesplusmod            |1.16.4_0.1.0        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TbscClick-MC1.16.4-v2.1.1.jar                     |TbscClick                     |tbscclick                     |2.1.1               |DONE      |NOSIGNATURE
		LavaClearView-1.16.2-1.1.0.jar                    |Lava Clear View               |clearview                     |1.1.0               |DONE      |NOSIGNATURE
		smarthud-1.1-1.16.3.jar                           |Smarter HUD                   |smarthud                      |1.1-1.16.3          |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		Mantle-1.16.5-1.6.92.jar                          |Mantle                        |mantle                        |1.6.92              |DONE      |NOSIGNATURE
		Inspirations-1.16.5-1.2.2.jar                     |Inspirations                  |inspirations                  |1.2.2               |DONE      |NOSIGNATURE
		shulkerdropstwo_1.16.5-1.4.jar                    |Shulker Drops Two             |shulkerdropstwo               |1.4                 |DONE      |NOSIGNATURE
		ShulkerTooltip-1.9.7.jar                          |Shulker Tooltip               |shulkertooltip                |1.9.7               |DONE      |NOSIGNATURE
		collective-1.16.5-2.25.jar                        |Collective                    |collective                    |2.25                |DONE      |NOSIGNATURE
		DoubleSlabs-1.16-3.5.0rc1.jar                     |Double Slabs                  |doubleslabs                   |3.5.0rc1            |DONE      |NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.2.2.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.2.2               |DONE      |NOSIGNATURE
		Chunk Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |DONE      |NOSIGNATURE
		WirelessRedstone-1.16.3-1.0.1.jar                 |Wireless Redstone             |wirelessredstone              |1.16.3-1.0.1        |DONE      |NOSIGNATURE
		expandedstorage-3.0.5+1.16.3.jar                  |Expanded Storage              |expandedstorage               |3.0.5               |DONE      |NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.3.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.3      |DONE      |NOSIGNATURE
		chunkloaders-1.1.7-mc1.16.5.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.7               |DONE      |NOSIGNATURE
		FriendlyFire-1.16.5-7.0.2.jar                     |FriendlyFire                  |friendlyfire                  |7.0.2               |DONE      |NOSIGNATURE
		betterbedrockgenerator-1.16.4-0.1.1.jar           |Better Bedrock Generator      |betterbedrockgenerator        |0.1.1               |DONE      |NOSIGNATURE
		InventoryEssentials_1.16.3-2.3.1.jar              |Inventory Essentials          |inventoryessentials           |2.3.1               |DONE      |NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |DONE      |NOSIGNATURE
		speedyladders-1.16.5-2.jar                        |Speedy Ladders                |speedyladders                 |1.16.5-2            |DONE      |NOSIGNATURE
		MineMenu-1.16.4-1.8.7.jar                         |MineMenu                      |minemenu                      |1.16.4-1.8.7        |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		CodeChickenLib-1.16.4-3.5.1.408-universal.jar     |CodeChicken Lib               |codechickenlib                |3.5.1.408           |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.4-2.7.1.166-universal.jar       |EnderStorage                  |enderstorage                  |2.7.1.166           |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CleanView-1.16.5-v1a.jar                          |CleanView                     |cleanview                     |1.16.5-v1a          |DONE      |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		hud_quiver-1.1.jar                                |HUD Quiver                    |hud_quiver                    |1.1                 |DONE      |NOSIGNATURE
		bigbuckets-1.1.5.jar                              |BigBuckets                    |bigbuckets                    |1.1.5               |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.0.105.jar           |Better Advancements           |betteradvancements            |0.1.0.105           |DONE      |NOSIGNATURE
	Crash Report UUID: f5fd62f4-16a0-4338-9896-c60ca627ea12
	Player Count: 1 / 8; [ServerPlayerEntity['helloua'/229, l='ServerLevel[2021]', x=-136.96, y=30.00, z=-293.56]]
	Data Packs: vanilla, mod:enchantedbookredesign (incompatible), mod:vanillaextension (incompatible), mod:theoneprobe, mod:swingthroughgrass (incompatible), mod:toolbelt (incompatible), mod:supermartijn642configlib, mod:preciseblockplacing, mod:torchslabmod (incompatible), mod:jei, mod:invtweaks (incompatible), mod:curios, mod:mantle (incompatible), mod:shulkerdropstwo, mod:goldenhopper (incompatible), mod:shulkertooltip (incompatible), mod:collective, mod:clumps, mod:journeymap (incompatible), mod:controlling, mod:jumpoverfences, mod:doubleslabs (incompatible), mod:inventoryhud, mod:chunkpregen, mod:wirelessredstone (incompatible), mod:expandedstorage, mod:randompatches, mod:torchoptimizer, mod:advancedtools, mod:coordinatesplusmod, mod:chunkloaders, mod:friendlyfire (incompatible), mod:betterbedrockgenerator, mod:inventoryessentials (incompatible), mod:charm, mod:forge, mod:inspirations (incompatible), mod:speedyladders (incompatible), mod:minemenu, mod:fastleafdecay (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:cleanview (incompatible), mod:tbscclick, mod:clearview, mod:hud_quiver, mod:smarthud (incompatible), mod:bigbuckets (incompatible), mod:betteradvancements, mod:caelus, mod:easyelytratakeoff, mod:curiouselytra
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.283 High
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by CJMinecraft01** [comment]
Hi, thanks for reporting this issue. I am aware of this but fixing this may take longer than I expected. The version you are currently using is an experimental pre release version which aims to improve the performance of the mod. To improve so, I had to change how the mod interacts with tile entities and unfortunately this issue has arose because of that change. I recommend switching back to the previous version where everything is working while I try to fix this; however since it is a change of the internal workings, it may take a while (especially as I am quite busy in real life at the moment). I apologise for the inconvenience that this will cause.

**Comment by Helloua4** [comment]
Thanks for the quick reply.
Very understandable, no worries.

I've installed the previous version (DoubleSlabs-1.16-3.4.10 I believe) and it's seems to be working splendidly.
Thanks again.
