### ISSUE TITLE
Vertical Campfire crashing game 1.16.5 latest

### ISSUE THREAD

**Issue by SHXRKIEgg** [CJMinecraft01/DoubleSlabs#182]
Hi, are you able to fix this issue?
Description: Ticking block entityDescription: Ticking block entity
java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{doubleslabs:vertical_slab} at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A} at net.minecraft.tileentity.CampfireTileEntity.func_73660_a(SourceFile:42) ~[?:?] {re:classloading} at cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_73660_a(SlabTileEntity.java:189) ~[doubleslabs:3.5.0rc1] {re:mixin,re:classloading}

**Comment by CJMinecraft01** [comment]
This is fixed in 1.16-3.5.0rc2 :)
