### ISSUE TITLE
Placing a campfire on top of a lower slab causes a crash *and breaks the save*

### ISSUE THREAD

**Issue by enduum** [CJMinecraft01/DoubleSlabs#183]
Using DoubleSlabs version 3.5.0c1, placing a vanilla campfire or soul campfire on top of any lower slab causes a freeze and then a crash. I haven't tried _every_ slab in the game but I've tested with a large variety of vanilla and modded slabs and it has crashed with every single one.

**It also breaks the save game with the crashed campfire.** Trying to load into that world later causes another freeze then crash.

DoubleSlabs version 3.4.10 does not have this issue, and rolling back to that version makes the save playable again.

**Edit:** Removing 3.5.0c1 also restores the save. However if you then close the game, reenable the mod, and load that world *again* you'll have the missing textures grid wherever your former mixed slabs were, and clicking any of these broken texture cubes crashes the game again.

**Another edit:** Uh, apparently "fixing" a world by rolling back to the older DoubleSlabs version results in all your mixed-slab upper campfires doing this, both old ones and newly placed ones: [[Screenshot]](https://i.postimg.cc/Hk3mhphg/2021-04-21-13-07-31.png)

[Log](https://pastebin.com/09zX5jAq) and [Crash Report](https://pastebin.com/wPenzZb8) from initially placing the campfire
[Log](https://pastebin.com/N02Rv9d0) and [Crash Report](https://pastebin.com/CNULRWu6) from trying to load the world that crashed

Minecraft 1.16.5
Tested with both Forge 36.1.0 (recommended) and 36.1.4 (latest)
Tested on a clean install with no other mods

**Comment by CJMinecraft01** [comment]
Hi there, thanks for reporting this and I sincerely apologise for these issues. The RC versions are experimental versions designed to try and improve performance hence they are not 100% stable. Please try 3.5.0rc2 as I believe this fixes the campfire issue (but please backup your world). Regarding the rendering issue, does it occur when shaders are disabled? Also, regarding the missing textures, if you bring up the F3 screen and look to the right, I'm guessing you see that the block is null? Unfortunately there's no way of restoring this without using a set block command to replace the block. I will look into this for you though and apologies again

**Comment by enduum** [comment]
-Campfire crash is fixed with 3.5.0rc2!
-Rendering issue only seems to occur with shaders active: [[shaders on]](https://i.postimg.cc/02HrZqvV/2021-05-06-12-00-19.png) ~~[[shaders off]](https://i.postimg.cc/QMvpzTrn/2021-05-06-11-42-09.png)~~ (Edit: I goofed, here's the one with no shaders: [[link]](https://i.postimg.cc/KvYRn86K/2021-05-06-12-00-48.png))
-Yes, F3 on the missing textures block shows null [[link]](https://i.postimg.cc/QMvpzTrn/2021-05-06-11-42-09.png), and while checking this just now I discovered that the bugged block is only visible with optifine installed. Without optifine the bugged block is still there, it still shows an outline when looked at, and still crashes the game when clicked, but it's invisible and lying in wait to mess you up when you least expect it, lol.
-My save is fine now, I restored from an old backup. 😅 Thank you for the concern, though.

**Comment by CJMinecraft01** [comment]
Glad to hear that the campfire is fixed! If you ever encounter the purple and black texture with the slabs just check the F3 screen to see if the state is null. If so then unfortunately an issue has occurred with the block and so the only fix is to setblock. In regards to the rendering issue, with campfires, your screenshot shows the one with the null state, would you be able to check by placing another campfire. Thanks again for all this :)
