### ISSUE TITLE
Vertical Corners Are Invisible (1.16.5)

### ISSUE THREAD

**Issue by ghost** [CJMinecraft01/DoubleSlabs#184]
When two different slabs are vertical and used in corners, it shows as invisible. I have only this mod on.

> Forge: (1.16.5) 36.0.42
> DoubleSlabs: (1.16.5 / April 13th upload) 1.16-3.5.0rc1

![2021-04-28_01 10 32](https://user-images.githubusercontent.com/83337735/116370257-10f4c180-a7bf-11eb-97ba-e6f3d4186c55.png)
![2021-04-28_01 10 37](https://user-images.githubusercontent.com/83337735/116371169-fd962600-a7bf-11eb-9873-cc0db7ff511e.png)
![2021-04-28_01 10 51](https://user-images.githubusercontent.com/83337735/116371194-0555ca80-a7c0-11eb-8a38-5af29e5214d0.png)

**Comment by ghost** [comment]
Before I place the vertical slab.
![2021-04-28_00 59 09](https://user-images.githubusercontent.com/83337735/116372284-1eab4680-a7c1-11eb-99e1-de6c061d549f.png)
Other photo
![2021-04-28_01 10 26](https://user-images.githubusercontent.com/83337735/116372341-2bc83580-a7c1-11eb-8d92-f4c34844cf05.png)

**Comment by ghost** [comment]
and this
![2021-04-28_01 32 38](https://user-images.githubusercontent.com/83337735/116373062-de989380-a7c1-11eb-9688-d971a82e7bf5.png)
![2021-04-28_01 32 59](https://user-images.githubusercontent.com/83337735/116373090-e5270b00-a7c1-11eb-93a0-d1b611145ea6.png)

**Comment by CJMinecraft01** [comment]
Apologies for the delayed reply, I believe that this should now be fixed in the latest version!! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
