### ISSUE TITLE
nearly impossible to place normal slabs

### ISSUE THREAD

**Issue by Novid33** [CJMinecraft01/DoubleSlabs#185]
i dont know if im missing something but i find it nearly impossible to place slabs normally. also campfires crash the game, becuase of this the mod is practically unusable. also, sideways campfires dont even make any sense! just remove it and it would make more sense and there would be no more crashing.

**Comment by CJMinecraft01** [comment]
Hi there! I apologise for the issues you are facing, I believe that the campfire issue is fixed in the newest version and I have added a method of vertical slab placement where you can toggle between placing vertical and horizontal slabs. Hope that helps! :)
