### ISSUE TITLE
Mod eating up 8GB allocated RAM in seconds

### ISSUE THREAD

**Issue by Reael** [CJMinecraft01/DoubleSlabs#187]
We use many mods, most of them are functional mods and scripts yet we had no issues so far. I was working on a huge hall and I was so happy to find this mod, happy enough to throw out block carpentry (since placing and then breaking a block carpentry slab together with another slab made the game crash, which isn't the issue right now) but after building up one wall this mod became extremely RAM hungry.
I had 6GB RAM allocated to Minecraft and first, it took like 4 minutes to munch down all the RAM while working on my building before freezing for app. 30 seconds to clear occupied RAM. I kept going but the timeframe it took to consume all the RAM got shorter with every freeze. After just 10 minutes in-game I need to restart Minecraft as it becomes unplayable, freezing every 5 seconds while freezes take longer and longer to a point where I actually get thrown from the server due to a time out.
I try to keep an eye on the RAM usage while f3 is enabled and I can't get less than 70% RAM usage when near my building. I'm fine outside of the chunk or at my friend's location and he has a lot of stuff going on with the create mod, applied energetics and immersive engineering and we don't have a problem.
I think a mod adding the possibility to merge slabs together shouldn't consume more RAM than a mod that allows building heavy machinery with animated visuals, then again I don't really know what makes this mod eat so much RAM.
I have allocated 8GB RAM to Minecraft now with the newest version of this mod for 1.16.4 but nothing much changes. I might be able to play a little longer (like 5 minutes) before it gets unplayable but otherwise, It doesn't change much and I actually don't want to allocate more RAM to Minecraft. I even disabled my shader, resource pack and set all my graphic settings to potato but it's not helping much. I don't have anything else going on in my chunk, I have no types of machinery working, nothing that needs a lot of render or RAM usage. It's just a big ol' castle on a big ol' mountain that's not even furnished yet so idk what is consuming so much RAM :(
I hope this can be fixed somehow because without the freezes and the RAM munchies this is one of my fav mods and I wouldn't want to throw it out of the list at all.

**Comment by CJMinecraft01** [comment]
Hi there, thanks for the report. I'm currently experimenting with ways to improve performance. I believe I understand where the performance impact is coming from and so I am trying to address this. Please try 3.5.0rc2 to see if this improves performance further. Please backup your world before upgrading as these are experimental versions. If you could potentially send your world file and mod list / mod pack link so I can test it directly on my machine, that would be amazing?

**Comment by Reael** [comment]
I'll try with the new version. If it keeps munching down on the RAM so badly I'll try to send you my world file and mod list :)

**Comment by CJMinecraft01** [comment]
Okay brilliant! Thank you :)

**Comment by CJMinecraft01** [comment]
Hi there! I've made some further improvements and so I'm going to close this issue. Thank you again for reporting this :) For now the update is only for 1.16 but I will be backporting to older versions as soon as I can :)
