### ISSUE TITLE
Gamecrash when interacting with campfire in any way

### ISSUE THREAD

**Issue by Reael** [CJMinecraft01/DoubleSlabs#188]
The newest version for 1.16.4
The mod crashes the game even if no slabs at all have been placed in the entire world if a left or right click is made on a campfire. Well it freezes the game, after waiting for over 30 minutes for the game to finally crash I had to close it via task manager, therefore no crash report has been generated. I tried several times with and without this mod and it only freezes to death with this mod. On the second try I was in a completely new flat creative world and haven't done anything else but placed a campfire and wanted to put out the fire with a shovel and it froze. No other interaction, no other item in my inventory, no other blocks around

**Comment by CJMinecraft01** [comment]
Hi there, apologies for the delayed response. Would you mind testing this in the latest version? I'm assuming you was using RC1 (it was an experimental version to try and fix an issue with performance)? Please try 3.5.0rc2 (bit backup your world first just in case). These are experimental versions that are me testing a performance increase. Sorry for the inconvenience

**Comment by Reael** [comment]
It seems like it works with the very newest version without crashing, at least it doesn't freeze on direct interaction with fire. I tried placing multiple fires, stack them, on the wall, on the floor, on slabs and it didn't freeze. But there is a texture glitch now with crimson and warped slabs now as soon as they are placed vertical (I'm using a self-made texture pack). Should I open a new issue about it?

**Comment by Reael** [comment]
Ok it took 5 fireplaces on the server to crash. It works in an empty world with only a few slabs but it crashed me out of the server and I can't log back in.
At least this time I got a crashlog:
https://pastebin.com/9QcC6aQi

**Comment by CJMinecraft01** [comment]
Brilliant! Does the other issue occur when reloading textures or after a restart? If not, please open a separate issue about it :)

**Comment by CJMinecraft01** [comment]
Must have missed your other comment, could you try this in 3.5.0rc2?

**Comment by Reael** [comment]
Was my mistake >< I uploaded the new version to the server but restarted the server before it was done deleting the old version. Funnily enough, I could join the server but it ran with the old file and my client had the new file. I fixed it just now and haven't had another issue with crashes till now. Sorry for my dumbass

**Comment by CJMinecraft01** [comment]
No problem! Glad it's resolved!
