### ISSUE TITLE
Mod lädt beim forge nicht

### ISSUE THREAD

**Issue by Shagum96** [CJMinecraft01/DoubleSlabs#19]
Ich habe den forge modloader mit einigen anderen mods installiert.
Der double slabs mod wird in minecraft in mods nicht angezeigt, demzufolge kann ich ihn auch nicht benutzen.
Woran liegt der Fehler?

**Comment by CJMinecraft01** [comment]
Für welche Minecraft Ausführung? (Mein Deutsch ist nicht sehr gut)
