### ISSUE TITLE
Texture Pack issue 1.16.

### ISSUE THREAD

**Issue by Reael** [CJMinecraft01/DoubleSlabs#190]
As requested I'm opening a new issue. Mod is the current 0rc2 version. It doesn't appear without a texture pack. I guess the issue lays within the fact that Mojang changed names of some textures between 1.14. and 1.16. hence leading to this issue because the names may still be messed up in my texture pack. However, I don't know what to do about it.
When placed normally, slabs have the proper textures, but when placing warped and crimson slabs vertically they have a mashed up texture.
The crimson slab texture includes the top and bottom of the jukebox texture, the actual crimson planks texture and the crimson roots texture.
The warped slab texture includes the striped spruce wood texture, the actual warped planks texture and the warped roots texture.
I don't think this is generally an issue of a mod, more an issue of the texture pack so it'd be nice if someone could maybe point me into the right direction to fix this within my texture pack.
I also thought it might be an optifine/shader issue so I tried with and without and the issue persists.
![texture_issue](https://user-images.githubusercontent.com/19366611/117360156-bba06a80-aeb8-11eb-8044-d926aad89d1e.png)

**Comment by CJMinecraft01** [comment]
Hi, thanks for reporting the issue! Would you mind testing to see if disabling the lazy model rendering for crimson and warped will fix your issue?
You simply need to override one of the tags for double slabs found in: `doubleslabs/tags/blocks/plank_slabs.json`. Removing the crimson and warped slabs may fix this? Here's the current one: https://github.com/CJMinecraft01/DoubleSlabs/blob/1.16.x/src/main/resources/data/doubleslabs/tags/blocks/plank_slabs.json
(I think you need to make a data pack for it but not 100% certain)

**Comment by CJMinecraft01** [comment]
Hi there! I believe that this is fixed in the latest version.. For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
