### ISSUE TITLE
Vanilla wood vertical slabs render broken on newest optifine preview with shaders

### ISSUE THREAD

**Issue by CallieEZ** [CJMinecraft01/DoubleSlabs#191]
![2021-05-06_13 27 58](https://user-images.githubusercontent.com/49820257/117361516-fbdafb00-ae6e-11eb-8c1f-9b4c2407acf6.png)
As the title says, the vertical wood slabs of just vanilla woods are broken with shaders in the newest optifine preview, none of the other vertical slabs are bugged. This screenshot was taken with just optifine and double slabs

**Comment by CallieEZ** [comment]
*1.16 rc2 and 1.16 optifine preview

**Comment by CJMinecraft01** [comment]
Does this persist if the shaders are disabled?

**Comment by CallieEZ** [comment]
No, however it does affect all shaders I've tested it with

**Comment by CallieEZ** [comment]
Seems to also effect the release version of optifine g8

**Comment by CJMinecraft01** [comment]
Apologies for the delay, this should be fixed in the latest version! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
