### ISSUE TITLE
Double slabs texture bugged when using shaders

### ISSUE THREAD

**Issue by TheCarpe** [CJMinecraft01/DoubleSlabs#192]
The double slabs textures are not working when I'm using any shaders, I did two tests:
That's with SEUS renewed (on/off)
![2021-05-19_07 28 23](https://user-images.githubusercontent.com/84450064/118805361-db01a500-b873-11eb-8c72-161a03b552d1.png)
![2021-05-19_07 28 47](https://user-images.githubusercontent.com/84450064/118805368-dc32d200-b873-11eb-8a66-edfd97d3cc74.png)

And that's with BSL 7.2 (on/off)
![2021-05-19_07 25 06](https://user-images.githubusercontent.com/84450064/118805130-90802880-b873-11eb-919b-d74d897c4856.png)
![2021-05-19_07 25 32](https://user-images.githubusercontent.com/84450064/118805133-9249ec00-b873-11eb-8c25-89263a7e3452.png)

I'm also getting the OpenGl Error: 1281(invalid value)
All my drivers and mods are up to date.

**Comment by CJMinecraft01** [comment]
Apologies for the delayed response but I believe this is fixed in the latest version! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :) Thank you for your patience
