### ISSUE TITLE
Possible Conflict with OTG

### ISSUE THREAD

**Issue by Swandar** [CJMinecraft01/DoubleSlabs#193]
It works just fine when I am playing on a vanilla world, but if I'm playing on an OTG world things start breaking.

If I place down 2 stone slabs on top of each other the game crashes and leaves behind the checkerboard texture. If I rejoin the world it only plays for a few seconds before crashing again.  

https://paste.dimdev.org/nitetacimu.mccrash
![image](https://user-images.githubusercontent.com/19779837/119578412-7c17c080-bd8a-11eb-8648-970a0566be65.png)

**Comment by Swandar** [comment]
Jumping back one version seems to have solved the problem

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay, this is now fixed in the latest version. Thank you for your patience
