### ISSUE TITLE
Verticle Slabs Texture not working

### ISSUE THREAD

**Issue by AlchemicalAlek** [CJMinecraft01/DoubleSlabs#194]
For some reason, no idea why, the texture is utterly broken for all wooden slabs (oak, spruce, warped, etc.) while all others work perfectly fine.

I am using other mods and maybe I had something installed that messed up the texture, so I will also include a screenshot of the mods and libs installed

![billede_2021-05-31_180321](https://user-images.githubusercontent.com/85124557/120218716-744c9600-c23a-11eb-8a73-87d8f73e858f.png)
![billede_2021-05-31_180331](https://user-images.githubusercontent.com/85124557/120218735-7a427700-c23a-11eb-8a90-9ccc846f72d7.png)
![billede_2021-05-31_180444](https://user-images.githubusercontent.com/85124557/120218873-a5c56180-c23a-11eb-88c1-01954e336ac7.png)

**Comment by AlchemicalAlek** [comment]
This is SO bizarre

![billede_2021-05-31_185112](https://user-images.githubusercontent.com/85124557/120222981-238c6b80-c241-11eb-9730-e4765cc17606.png)

**Comment by mcircuit** [comment]
Hello,

I ran into the same rendering issue while trying out the mod. All the wooden slabs would appear glitched as you have posted whenever I ran any shaders. It would render normally without any shaders on.

The fix I found was the following; in the config file of the mod, you will find an option for lazy vertical slabs. Remove the wooden slabs from there as shown below, and it might fix the rendering issue. It did for me.

Cheers!
![Screenshot 2021-05-31 232226](https://user-images.githubusercontent.com/85128923/120227637-2ac67000-c267-11eb-8b42-7682f0672384.png)

**Comment by AlchemicalAlek** [comment]
Thanks for the fix! Much appreciated!! How do I enter the config? The button wont work

**Comment by mcircuit** [comment]
In your minecraft folder, you will find a config folder as shown below:
![image](https://user-images.githubusercontent.com/85128923/120365563-39c32600-c32c-11eb-9313-6fe0105f61ff.png)

In the config folder, you will find the double slabs client config file in .toml format, as shown below:
![image](https://user-images.githubusercontent.com/85128923/120365657-5a8b7b80-c32c-11eb-95ae-5f26071255e4.png)

Open it using an editor (I used notepad++), and do the edit I had mentioned earlier. And voila!
Hope this works for you too!

Cheers!

**Comment by AlchemicalAlek** [comment]
Okay, thank you, very much appreciated!!

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay but I believe that this is fixed in the latest version :) For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
