### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by VoxelCreatesStuff** [CJMinecraft01/DoubleSlabs#196]
See below. I would realy apprecieate your help!

[14:35:15] [Server thread/DEBUG] [FML]:&nbsp;Registering @EventBusSubscriber for cjminecraft.doubleslabs.client.proxy.ClientProxy for mod doubleslabs
--
547 | [14:35:15] [Server thread/ERROR] [FML]:&nbsp;An error occurred trying to load an EventBusSubscriber cjminecraft.doubleslabs.client.proxy.ClientProxy for modid doubleslabs
548 | java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
549 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292]
550 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292]
551 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_292]
552 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_292]
553 | at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
554 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:?]
555 | at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612) [FMLModContainer.class:?]
556 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
557 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
558 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
559 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
560 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
561 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
562 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
563 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
564 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
565 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
566 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
567 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
568 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
569 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
570 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
571 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
572 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
573 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
574 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
575 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
576 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
577 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
578 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
579 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
580 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
581 | at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) [Loader.class:?]
582 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
583 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
584 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
585 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
586 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
587 | Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
588 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
589 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
590 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
591 | ... 38 more
592 | Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer&nbsp;net.minecraftforge.fml.common.asm.transformers.SideTransformer@6fe46b62 from coremod FMLCorePlugin
593 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge.jar:?]
594 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
595 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
596 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
597 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
598 | ... 38 more
599 | Caused by: java.lang.RuntimeException: Attempted to load class cfy for invalid side SERVER
600 | at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge.jar:?]
601 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge.jar:?]
602 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
603 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
604 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
605 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
606 | ... 38 more
607 | [14:35:15] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]:&nbsp;Encountered an unexpected exception
608 | net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
609 | &nbsp;
610 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89) ~[forge.jar:?]
611 | at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612) ~[forge.jar:?]
612 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
613 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
614 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
615 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
616 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
617 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
618 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
619 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
620 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
621 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
622 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
623 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
624 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
625 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
626 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
627 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
628 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
629 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
630 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
631 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
632 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
633 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
634 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
635 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
636 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
637 | at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) ~[Loader.class:?]
638 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
639 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
640 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
641 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
642 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
643 | Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
644 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292]
645 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292]
646 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_292]
647 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_292]
648 | at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
649 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
650 | ... 32 more
651 | Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
652 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
653 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
654 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
655 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292]
656 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292]
657 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_292]
658 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_292]
659 | at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
660 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
661 | ... 32 more
662 | Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer&nbsp;net.minecraftforge.fml.common.asm.transformers.SideTransformer@6fe46b62 from coremod FMLCorePlugin
663 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge.jar:?]
664 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
665 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
666 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
667 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
668 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292]
669 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292]
670 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_292]
671 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_292]
672 | at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
673 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
674 | ... 32 more
675 | Caused by: java.lang.RuntimeException: Attempted to load class cfy for invalid side SERVER
676 | at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge.jar:?]
677 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge.jar:?]
678 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
679 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
680 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
681 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
682 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292]
683 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292]
684 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_292]
685 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_292]
686 | at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
687 | at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
688 | ... 32 more
689 | [14:35:15] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]:&nbsp;This crash report has been saved to: /server/./crash-reports/crash-2021-06-08_14.35.15-server.txt
690 | [14:35:15] [Server thread/INFO] [net.minecraft.server.MinecraftServer]:&nbsp;Stopping server
691 | [14:35:15] [Server thread/INFO] [net.minecraft.server.MinecraftServer]:&nbsp;Saving worlds

**Comment by D3nnis3n** [comment]
0.10 works, so you could use that version for now.

**Comment by CJMinecraft01** [comment]
Hi there! I believe that this is now fixed in the latest version :)
