### ISSUE TITLE
FPS drops, freezes, server crashes

### ISSUE THREAD

**Issue by kubsqwer** [CJMinecraft01/DoubleSlabs#198]
So basically the more vertical slabs I place the more laggy it is
Restarting the game usually helps but only for about 30-60 minutes, sometimes less sometimes more
sometimes it gets to the point i spend more time looking at frozen game than actually playing and restarting the game over and over for a minor change is annoying

Also, sometimes a vertical slab for some reason becomes invisible (sometimes seemingly for no reason and sometimes while interacting with other mods) when you break such invisible vertical slab either your game or everybody's on the server game crashes
i'm attaching the crash report but game freezing is a bigger problem

Thank you in advance
[crash-2021-06-21_17.55.03-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/6687949/crash-2021-06-21_17.55.03-client.txt)

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for the bug report, before you crashed, did the block you were interacting with have a purple and black texture? Or was it simply invisible? Did the slab randomly turn invisible or could you show me what you did to turn the slab invisible? Also, have you tried this on the latest version (3.5.0)? Apologies that's a lot of questions..

**Comment by CJMinecraft01** [comment]
Hey again! I believe that I have fixed this now in the latest version :)
