### ISSUE TITLE
Crash when placing slabs.

### ISSUE THREAD

**Issue by TarnishedSoul** [CJMinecraft01/DoubleSlabs#199]
Hi, I've been crashing when placing slabs. I'm on 1.12.2 and Vanillafix told me it was an issue between Improvable Skills 3 and Double Slabs, so I removed Improvable Skills but the crash persisted, this time showing a magenta-error block before I crash.

This is the crash I got when Improvable Skills 3 was still installed: https://paste.dimdev.org/ohajunesef.mccrash
This is the crash I got when the magenta-error block showed up: https://paste.dimdev.org/sisuciraqu.mccrash

**Comment by TarnishedSoul** [comment]
Reverting to a previous version seems to have fixed the issue for now.

**Comment by CJMinecraft01** [comment]
Thanks for reporting this! This is now fixed in the latest version :)
