### ISSUE TITLE
ES-ES (Spanish) LANG

### ISSUE THREAD

**Issue by 16N1CO** [CJMinecraft01/DoubleSlabs#200]
{
  "itemGroup.verticalslabs": "Losas verticales",
  "item.vertical_slab.prefix": "Vertical %s",
  "doubleslabs.keycategory": "Doble losas",
  "doubleslabs.key.toggleVerticalSlabPlacement": "Palanca de colocación de losa vertical",
  "doubleslabs.configgui.slabBlacklist": "Lista negra de losas horizontales",
  "doubleslabs.configgui.uvlockModels": "Modelos UVLock",
  "doubleslabs.configgui.verticalSlabBlacklist": "Liste negra de losas verticales",
  "doubleslabs.configgui.replaceSameSlab": "Reemplaza igual losa horizontal",
  "doubleslabs.configgui.disableVerticalSlabPlacement": "Desactivar colocación de losas verticales",
  "doubleslabs.configgui.verticalSlabCraftingBlacklist": "Lista negra de elaboración de losas verticales",
  "doubleslabs.configgui.lazyVerticalSlabModels": "Modelos de losas verticales perezosas",
  "doubleslabs.configgui.slabCullBlacklist": "Lista negra de eliminación de losas",
  "doubleslabs.configgui.useDoubleSlabModelBlacklist": "Modelos de losas verticales dobles",
  "doubleslabs.configgui.verticalSlabPlacementMethod": "Método de colocación de losas verticales"
}

**Comment by CJMinecraft01** [comment]
Hi there! Thank you, I will add this in the next version :)
