### ISSUE TITLE
Rendering issues with Sodium(Forge version).

### ISSUE THREAD

**Issue by YasonCore** [CJMinecraft01/DoubleSlabs#201]
Sodium version: https://github.com/AeiouEnigma/sodium-forge/releases/tag/v0.1.1-build1

![2021-06-27_10 31 04](https://user-images.githubusercontent.com/31430536/123534024-57b95600-d733-11eb-979b-13622e3a47ce.png)

This is probably due to the fact that Sodium changes the render. I don't know if it will be possible to fix this on your part or on the part of the author of the port.

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for reporting this, which mod version are you using?

**Comment by CJMinecraft01** [comment]
Also, would you mind checking if the latest version of sodium forge fixes this issue? I've just tested this and it appears to work
