### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by GerbilPL** [CJMinecraft01/DoubleSlabs#203]
Hi!
When I use Double Slabs on my 1.12.2 server (because of some other mods) it crashes. I also tried removing other mods but that did not work.

Here crash report (load.jar is just forge server/loader so i thats not important).

Thank you for this amazing mod anyways!
[crash.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/6791467/crash.txt)

**Comment by CJMinecraft01** [comment]
Hi there! This issue has been resolved in the latest version.. please update :)
