### ISSUE TITLE
SlabSupport.java should not use net.minecraft.client.Minecraft

### ISSUE THREAD

**Issue by wchen1990** [CJMinecraft01/DoubleSlabs#206]
This causes a startup error on dedicated servers, since the class does not exist for dedicated servers. If SlabSupport is supposed to be a client side utility, should probably change the call to reflect that in DoubleSlabs.java's constructor method.

**Comment by CJMinecraft01** [comment]
Thanks for reporting this, I'll update with your patch shortly.
