### ISSUE TITLE
Weird Campfire lighting absence

### ISSUE THREAD

**Issue by SethbotStar** [CJMinecraft01/DoubleSlabs#208]
![2021-07-29_04 42 05](https://user-images.githubusercontent.com/30171402/127471995-16992aac-ec9e-4f10-8da7-8af107305857.png)
So the doubleslabs campfire does not emit light and looks like this when put on non-transparent blocks and slabs... so it probably is mainly just that a light level needs to be added to blocks that contain a campfire.

(This is what it looks like at night, separated to really show the difference)
![2021-07-29_05 00 29](https://user-images.githubusercontent.com/30171402/127472751-29a4c745-6f2b-4e30-8be1-a674a12d83c1.png)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response. What minecraft and mod version are you using? :)

**Comment by SethbotStar** [comment]
It's no issue, i also have delayed responses from time to time, and you're working on mods and probably other things so yeah.

**I was using Double Slabs 1.16-3.5.3 with Forge 1.16.5 36.2.2**

It's my first time actually using double slabs, though it is in a modpack. I just assumed this was like an accidental oversight when adding campfires as a slab or something. (It only happens whenever using campfires as a slab, whenever normal the lighting and features of the campfire work properly.) I'm unfamiliar with how to add tags, or i would've added missing feature or something.

If the campfires slabs are meant to have lighting and 4 inventory slots and this is just a bug, then that's fairly odd, nice that the smoke is working though.

If i had to guess, i'd expect the same lack of behavior from every campfire slab, if this is a missing feature. I can try to test this as a standalone and/or with newer versions of the mod and/or forge.

Does seem like a very interesting mod though, i think other this i personally just need to tweak a few things to have things working very nicely.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extremely long delay in responding to this, I've had a really hectic year at university and have only just had the chance to take a look. From my own testing, I believe this is fixed in the latest version, if you wouldn't mind checking that would be great :)
