### ISSUE TITLE
Better Nether slabs render incorrectly 

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#214]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Double Slabs v3.7.1`
[`Better Nether Reforged vbeta2`](https://www.curseforge.com/minecraft/mc-mods/betternether-reforged)

Slabs from Better Nether Reforged render incorrectly as vertical slabs.

![2021-09-15_00 16 02](https://user-images.githubusercontent.com/12000593/133375236-da67b363-0476-4036-a8f5-4ef51700612b.png)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delayed response, I've had a hectic year at university and have only just got round to checking the issues with the mod. I have now fixed this I believe and will add the fix in the next version

**Comment by WenXin20** [comment]
No problem! College can be busy for sure
