### ISSUE TITLE
Lord of the Rings slabs render incorrectly

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#216]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Double Slabs v3.7.1`
[`Lord of the Rings v4.6`](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed)

Slabs from Lotr render incorrectly as vertical slabs.

![2021-09-16_23 33 23](https://user-images.githubusercontent.com/12000593/133725167-08a44286-f41d-4d33-974d-c09e8ad489e5.png)

**Comment by Morabert** [comment]
I have this issue as well, _"LotR:Renewed"_ have integrated Slabs.
I've noticed that any mod that has integrated verticality for slabs has a render conflict (see: cushions in _"Wily Textiles"_ Mod)

**Comment by CJMinecraft01** [comment]
Thanks for the issue, the LOTR slabs should now place and appear correctly when I release the next version!
