### ISSUE TITLE
Prefab slabs render incorrectly

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#217]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Double Slabs v3.7.1`
[`Prefab v1.6.5.10`](https://www.curseforge.com/minecraft/mc-mods/prefab)

The grass slab and the glass slab from prefab both render incorrectly as vertical slabs.

![2021-09-17_01 46 50](https://user-images.githubusercontent.com/12000593/133737661-341beb10-f494-4bf9-b136-35ac5950cd1c.png)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the slow reply (as per your other issue). In regards to the grass slab issue, you need to add it to the `uvlockModelBlacklist` in the client config and that should fix the texture issue. I am looking into the glass slab issue now

**Comment by CJMinecraft01** [comment]
Fixed the glass slab issue, it seemed that the glass slab item was being recognised as a valid slab so it allowed the slab to be placed vertically, but the glass slab block wasn't recognised so no vertical slab variant was generated. This will be fixed in the next update

**Comment by WenXin20** [comment]
Thanks!
