### ISSUE TITLE
[1.16.5] Crash randomly

### ISSUE THREAD

**Issue by Axelouuu-dev** [CJMinecraft01/DoubleSlabs#219]
Hey !

I repport that issue because I don't know how what appends and how to fix it :o 

# crash logs # 
https://pastebin.com/M8Td8EBV

**Comment by wavy-cat** [comment]
The same problem in 2022.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extreme delay in responding to this issue. I've been really hectic at university this year and have only just had a chance to look through the issues. I think I have fixed this and will add the fix in the next version.
