### ISSUE TITLE
Minecraft 1.15.2 - 2.0.3 server crashing

### ISSUE THREAD

**Issue by iN0053** [CJMinecraft01/DoubleSlabs#22]
Today my server community came across a consistent crash after updating from version 2.0.2 to 2.0.3.

It appears our turtle pen, built utilizing the double slabs mod was causing a server crash, we had to eventually /kill @e all the turtles in the area to prevent the server crash for players in the area. We've had been playing with 2.0.2 for a while without this issue and the double slabs mod is the only relevant mod we updated this week.

Attached are two of the crash logs, as well as some pics of the build if at all relevant.
[crash-2020-03-29_15.33.20-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4400087/crash-2020-03-29_15.33.20-server.txt)
[crash-2020-03-29_15.39.57-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4400088/crash-2020-03-29_15.39.57-server.txt)

https://imgur.com/a/3pZtPEq

Not a major issue as we can avoid the crash by disabling the farm.

**Comment by CJMinecraft01** [comment]
Sorry for the delay, upon looking into this I've discovered a really simple error I had made when porting to 1.15 (a method got renamed but the old one was now client side only). This will be fixed in the latest version!
