### ISSUE TITLE
Crash when mining 1.5 height block of slabs

### ISSUE THREAD

**Issue by DrUltraLux** [CJMinecraft01/DoubleSlabs#225]
Crash when mining a triple slab. It tries to render a single block and gets confused. Needs a 1.5 height block for mining triple slabs. 
It renders purple and black squares right before the crash. 

[crash-2021-11-02_07.47.27-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/7456116/crash-2021-11-02_07.47.27-client.txt)

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extremely long delay in response, I've had a hectic year at university and have only just had chance to look at the issues with the mod. I believe I have just fixed this so this should be fixed in the next version
