### ISSUE TITLE
Port 1.18

### ISSUE THREAD

**Issue by Flexz9** [CJMinecraft01/DoubleSlabs#228]
Would it be possible to port to 1.18? As far as I understood of other mods it's not too different from 1.17.

Thank you for this amazing mod!

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the delay in responding to this. It took me a while to update the mod, primarily due to irl commitments (I've had a hectic year at university this year). You should see that there is now a 1.18 (and 1.19) version of the mod. Again, sorry for the delay
