### ISSUE TITLE
Double slabs freezing mobs whilst using performant

### ISSUE THREAD

**Issue by h4vok-git** [CJMinecraft01/DoubleSlabs#233]
I have discovered a bug when running performant alongside the double slabs mod, when using performant on my server alongside the double slabs mod (DoubleSlabs-1.16-3.5.2) it causes mobs to freeze they still collide with the player but cannot move whatsoever even breaking the slabs below them or using water results in the mob still being frozen in mid air as the mob is not affected by gravity. To replicate this issue i made a 3x3 acacia slab platform (the slabs were stacked on eachother resulting in it being a full block in height) and spawned mobs above the area which would result in them freezing. The most consistent way to get this glitch is to throw chicken eggs at the slabs which yields a 100% reproducible result. This issue is not present when running the double slabs mod on my server WITHOUT performant. NOTE: this effect can be seen by other players on multiplayer aswell.

i have also tested with the latest version of (3.7.2) of double slabs but this issue still persists.

** Mod version **
using forge 36.2.20, (1.16.5 multiplayer server) performant-1.16.2-5-3.81m 

https://user-images.githubusercontent.com/84686040/148288303-285f09ca-e20f-470a-a3ad-57db47c16610.mp4

**Comment by someaddons** [comment]
found the issue and left a note of whats happening/what should be fixed in a comment at https://github.com/someaddons/performant_issues/issues/215

**Comment by CJMinecraft01** [comment]
Thank you so much! I have changed what you suggested. Also I apologise for the delay in making this change, had a really hectic year at university so have only just got round to taking a look at all the issues with the mod. Sorry about that
