### ISSUE TITLE
[1.19] Error loading with 41.0.96

### ISSUE THREAD

**Issue by Baggytrousers27** [CJMinecraft01/DoubleSlabs#238]
Picked a heck of a time to debut in 1.19
As with 96% of forge mods versions 41.0.64 and 41.0.94 have breaking changes (no big surprise).

[Crashlog](https://pastebin.com/aqJzr7py)

**Comment by CJMinecraft01** [comment]
Thanks for reporting this, bad timing on my part. Have just published a new version which will fix this
