### ISSUE TITLE
[compatibility] Quark's Vertical Slabs

### ISSUE THREAD

**Issue by i-o-u** [CJMinecraft01/DoubleSlabs#24]
Could support for Quark's vertical slabs be added?

**Comment by CJMinecraft01** [comment]
I do plan to add vertical slabs to double slabs and when I do I will add compatibility with other mods such as with Quark

**Comment by WenXin20** [comment]
Mubble is another mod that adds vertical slabs.

**Comment by CJMinecraft01** [comment]
Support for both mods suggested has been added in the latest versions for 1.14/1.15
