### ISSUE TITLE
Keeping original slabs when they are not two different ones

### ISSUE THREAD

**Issue by D3nnis3n** [CJMinecraft01/DoubleSlabs#26]
Would there be a possibility to keep the minecraft or mod slabs when you do double slabs from the same type?

Everytime i place two normal stone slabs to get double slabs they now switch to doubleslabs, causing them to be displayed differently to the existing minecraft / mod double slabs due to SereneSeasons changing color and due to texturepacks.

I think it would only be required to use your slabs when i actually put two different ones together, otherwise using the original ones?

**Comment by CJMinecraft01** [comment]
This is entirely possible and I will hopefully add this as a configuration option soon!

**Comment by D3nnis3n** [comment]
That would be great, thank you very much for considering this. :)

**Comment by CJMinecraft01** [comment]
This has now been added in the latest version!
