### ISSUE TITLE
Bug With the doors

### ISSUE THREAD

**Issue by SoyJetixXD** [CJMinecraft01/DoubleSlabs#28]
Information: Hello, We see each other again, I use your mod with my friends to make some constructions in our survival and one of my friends discovered a small fault, in the slabs, they do not let us put the doors.

VANILLA:
![2020-04-09_18 04 47](https://user-images.githubusercontent.com/60457424/78950209-9eba1d80-7a93-11ea-82fc-aaba55c3d7f6.png)
DOUBLE SLABS:
![2020-04-09_18 49 20](https://user-images.githubusercontent.com/60457424/78950223-af6a9380-7a93-11ea-89af-24ec5e97531c.png)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!
