### ISSUE TITLE
Crash In Multiplayer

### ISSUE THREAD

**Issue by SoyJetixXD** [CJMinecraft01/DoubleSlabs#29]
Information: Hello, see you again, I was playing with my friend, until he told me that he was crashing the game, vanillafix said that there could be 2 nosy mods, and the crashing starts when he places the slabs several times.
Thank you for reading.
![Captura_de_pantalla_18](https://user-images.githubusercontent.com/60457424/78968455-40f4f800-7aca-11ea-9d3c-484865ffb2a2.png)
Link:https://paste.dimdev.org/uhokufuwig.mccrash

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
