### ISSUE TITLE
[1.12-0.3.1] Vanishing slabs

### ISSUE THREAD

**Issue by Pulz-TCP** [CJMinecraft01/DoubleSlabs#30]
Hi, on 0.3.1 I'm seeing a placement bug.

**Part one**
Placing two slabs on top of a _regular_ block is fine visually, but as per 'part two' of the report they will disappear.
Placing two slabs on top of a doubleslab or slab1/slab2 block causes it to either vanish and reappear in the inventory on the next place or causes the block below to be.
https://streamable.com/yjpvtd

**Part two**
Hitting any double slab block deletes the second slab, which reappears in your inventory the next time you place one down.
https://streamable.com/fpjrua

I snipped the start of my latest.log to where I started messing with the slabs:
http://files.theclassicpack.com/junk/latest.zip

**Comment by CJMinecraft01** [comment]
Could you please send a mod list for the mods that you are using?

**Comment by Pulz-TCP** [comment]
Sure, https://www.technicpack.net/modpack/the-classic-pack-beta/mods

**Comment by CJMinecraft01** [comment]
This should hopefully be fixed in the latest version!
