### ISSUE TITLE
(1.15.2) Aurum's More Blocks Incompatibillity

### ISSUE THREAD

**Issue by Opareds** [CJMinecraft01/DoubleSlabs#31]
When i try to mix two colors of glass slabs or one glass slab and any slab like smooth stone slab does this thing. At first image it is with any slab, left slab is without mixing. At right is mixing with vanilla slab. Second one is two glass slabs mixed.
![2020-04-10_22 13 15](https://user-images.githubusercontent.com/63459953/79016788-840da480-7b78-11ea-8608-a062d0061546.png)

![2020-04-10_17 02 07](https://user-images.githubusercontent.com/63459953/78996494-5eb77100-7b4d-11ea-843d-094863ec604c.png)

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
