### ISSUE TITLE
Game crashes whenever a block is right-clicked

### ISSUE THREAD

**Issue by Wakatsu** [CJMinecraft01/DoubleSlabs#32]
[crash-2020-04-12_16.27.17-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4466064/crash-2020-04-12_16.27.17-client.txt)
[crash-2020-04-12_16.18.01-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4466065/crash-2020-04-12_16.18.01-client.txt)

Game crashes whenever a block is right-clicked. Crashlog indicates this mod's erebus compatibility part being the case.

Please fix.

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
