### ISSUE TITLE
Game crashes when break double slabs

### ISSUE THREAD

**Issue by Cebasdian** [CJMinecraft01/DoubleSlabs#33]
Hi, everytime I break a double slab my game crash.
Can someone help me, please?
Thx
[crash-2020-04-12_23.56.35-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4467261/crash-2020-04-12_23.56.35-server.txt)

**Comment by CJMinecraft01** [comment]
Could you tell me which slabs you were trying to break when this happened please?

**Comment by Cebasdian** [comment]
It was a double smooth stone slab.
I didn't try to break different slabs.

**Comment by CJMinecraft01** [comment]
Have you tried this in the latest version. From your crash log it appears you are in version 0.1.4 for 1.12 but we are now on version 0.4.0

**Comment by Cebasdian** [comment]
Thank you! I don't know why I installed the wrong version but it is working now. Thanks ^^
