### ISSUE TITLE
Using /clone to copy multiple mixed slabs throws an error in chat & produces missing-texture blocks that cause crashes

### ISSUE THREAD

**Issue by floral-qua-floral** [CJMinecraft01/DoubleSlabs#35]
While testing for another issue, I noticed an issue when using /clone to duplicate a platform of mixed slabs. Crash report is available [here](https://paste.dimdev.org/enelovuqeg.mccrash). Another mod, Alternate Spawn System, is loaded because I'm trying to identify a potential conflict between them. That issue report will probably be posted soon, once I've finished identifying that problem. I don't believe that mod being present has any influence on this issue, so I haven't bothered testing this with only DoubleSlabs loaded - I can do that if requested, though.

Steps to reproduce:
1. Place a few mixed slabs somewhere
2. Use /clone to copy them somewhere else
3. Observe that most of them have a missing texture - when I tested, all but one did.

Attempting to break one of the blocks will instantly crash the game, even in Creative mode. This occurs regardless of whether the targetted block has its texture or not. /setblock cannot replace the block with air, and replacing it with any other block (i.e. stone) will output that it was successful, but the block will not change. Once this has occurred, though, it can be replaced with air using /setblock to properly remove the glitched block. Stepping on the block will also cause a crash (Crash report is available (here)[https://paste.dimdev.org/cebewesofe.mccrash]).

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
