### ISSUE TITLE
Crash with Alternate Spawn System

### ISSUE THREAD

**Issue by floral-qua-floral** [CJMinecraft01/DoubleSlabs#36]
A crash occurs when DoubleSlabs is loaded alongside [Alternate Spawn System](https://www.curseforge.com/minecraft/mc-mods/ass). Report is available [here](https://paste.dimdev.org/xucedujono.mccrash) - I believe it occurs when checking if a mixed slab is available for spawning, as I've only observed the issue happening once I've moved a reasonable distance away from the slab.

Steps to reproduce:
1. Install DoubleSlabs with Alternate Spawn System
2. Create a Superflat world with no blocks in it. I used a modified version of the default preset because I can't remember whether the special biome from the Void preset prevents monster spawns.
3. Ensure there are no spawnable surfaces nearby and make a big platform of mixed slabs. The one I made was about 4x9 blocks.
4. Set the time to night (I'm not sure if this step is necessary or not)
5. Move about 10-20 blocks or so away and just fly around a bit. It should take less than a few minutes for the game to crash - for me it was about 30 seconds after I moved away from the platform.

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!
