### ISSUE TITLE
Blacklisted slab (from other mod) causes crash

### ISSUE THREAD

**Issue by BlackQuests** [CJMinecraft01/DoubleSlabs#38]
When trying to place another slab on top of any slab from midnight the game will give the following crash:
https://paste.dimdev.org/urofubekaw.mccrash
I've blacklisted all of midnight's slabs and even tried to disable "Replace Same Slab". My blacklist looks like:
S:"Slab Blacklist" <
        midnight:shadowroot_slab
        midnight:dead_wood_slab
        midnight:dark_willow_slab
        midnight:nightstone_slab
        midnight:nightstone_brick_slab
        midnight:trenchstone_slab
        midnight:trenchstone_brick_slab
        midnight:dewshroom_slab
        midnight:viridshroom_slab
        midnight:nightshroom_slab
        midnight:rockshroom_bricks_slab
     > 

and here's the code relevant to the crash:
[getVariantProperty() code](https://github.com/Cryptic-Mushroom/The-Midnight/blob/30c5bf34dc8b0532e75fc48afc2b8e74d8874718/src/main/java/com/mushroom/midnight/common/block/BlockMidnightSlab.java#L52)

**Comment by BlackQuests** [comment]
I see that the method is being called here: [DoubleSlabsConfig.java#L37](https://github.com/CJMinecraft01/DoubleSlabs/blob/dd60dbad5821049b6d720f18773a5b74fa0ec4d6/src/main/java/cjminecraft/doubleslabs/DoubleSlabsConfig.java#L37)
Which I'm guessing is the cause of the crash, seeing as it is always run regardless of blacklisting (at least, that's my guess I don't know the full implementation). Is there a way to make a workaround for this?

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version! Thanks for the report!
