### ISSUE TITLE
Slabs with light values

### ISSUE THREAD

**Issue by cech12** [CJMinecraft01/DoubleSlabs#39]
I am the developer of the [Extended Mushrooms](https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms) mod and I like your mod! Our mods are really compatible. The only thing I noticed is: I added a slab block with a light value (Glowshroom Slab). 

When I place the Glowshroom Slab and on top of it for example an Oak Slab the light value is overridden and seems to be 0. 
The same thing happens when both slabs in a block have a light value (2 Glowshroom Slabs), which works correctly without your mod.

Mods: 
* Double Slabs 1.15-2.2.5
* Extended Mushrooms 1.3.0 - MC 1.15.2

**Comment by CJMinecraft01** [comment]
Hi, yes this is a feature which I've not yet implemented but I hope to do so soon and will put this out in the next version!

**Comment by CJMinecraft01** [comment]
Added in the latest version!

**Comment by cech12** [comment]
Nice thanks a lot!
