### ISSUE TITLE
Server crush 1.15.2

### ISSUE THREAD

**Issue by FuryOfFools** [CJMinecraft01/DoubleSlabs#43]
I have no idea why.
mod - 2.4.0 
[crash-2020-06-04_17.32.07-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4730353/crash-2020-06-04_17.32.07-server.txt)

**Comment by CHead2000** [comment]
Same Issue

Log: [2020-06-04-2.log.gz](https://github.com/CJMinecraft01/DoubleSlabs/files/4730633/2020-06-04-2.log.gz)

Crash Report: [crash-2020-06-04_14.15.10-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4730639/crash-2020-06-04_14.15.10-server.txt)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version! Sorry about that (I'd left some old redundant code in)

**Comment by FuryOfFools** [comment]
@CJMinecraft01 Sorry but new vertical slab feature still trigger server crash and massive lags. Maybe it was worth creating a new crash report, but the problem is almost the same.
Mod - 2.4.1
[crash-2020-06-05_00.09.52-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4732498/crash-2020-06-05_00.09.52-server.txt)

**Comment by CJMinecraft01** [comment]
I think I've spotted the issue and that should be resolved in the latest version! Sorry about that. Let me know if there are any further issues

**Comment by FuryOfFools** [comment]
Ok, the client on server starts to lag when I try to break the vertical slab. More precisely, the client simply dies. Heals only alt + f4. Is it normal that vertical slabs cannot be doubled?
Edit: Hmm... For some reason this is not happening anymore. Something is wrong here.

**Comment by CJMinecraft01** [comment]
Do you have the log to see what has errored? Also, which slabs were you trying to combine and which were you trying to break?

**Comment by FuryOfFools** [comment]
Sorry I forgot crash report and logs attached. I used prismarine slab, but I think which block I used is not very important.
[crash-2020-06-05_14.33.29-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4737577/crash-2020-06-05_14.33.29-client.txt)
[2020-06-05-2.log](https://github.com/CJMinecraft01/DoubleSlabs/files/4737666/2020-06-05-2.log)

I repeated the error. In survival mode, I break with a pickax cobblestone slabs like last time. Vertical slabs connected one to the other and I tried to break one of them and got the same error. Another time, I did not connect them, but I got the same error.
[crash-2020-06-05_21.47.17-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4737714/crash-2020-06-05_21.47.17-client.txt)
[latest.log](https://github.com/CJMinecraft01/DoubleSlabs/files/4737717/latest.log)

> Also, which slabs were you trying to combine and which were you trying to break?

My mistake is the second slab is put without pressing shift

**Comment by CJMinecraft01** [comment]
I've tried reproducing this myself and it feels very on occasion for me (it happens when I break the double variant). Try out the latest version and see if the error still persists.

**Comment by FuryOfFools** [comment]
Client is still dying

**Comment by CJMinecraft01** [comment]
Same error?

**Comment by FuryOfFools** [comment]
Yes
[crash-2020-06-07_20.08.08-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4742428/crash-2020-06-07_20.08.08-client.txt)

**Comment by CJMinecraft01** [comment]
Can you please check this still occurs in the latest version?

**Comment by FuryOfFools** [comment]
It works! It seems that somehow it does not break correctly with visual bugs, and sometimes it is absolutely normal, but it breaks and does not crash.
Sometimes after breaking a block a technical texture appears or the breaking animation freezes

**Comment by CJMinecraft01** [comment]
Yeah I've noticed this myself but I'm not too sure how I can fix this. I'll leave this issue open cause I've only fixed the crash and not the visual issue

**Comment by FuryOfFools** [comment]
@CJMinecraft01 I'd rather create a new one. Another problem anyway.
