### ISSUE TITLE
Improved stations disappear

### ISSUE THREAD

**Issue by ArturilloD** [CJMinecraft01/DoubleSlabs#45]
When placing two normal slab furnaces on top of each other, when they are extracted with a pick they disappear and a transparent block remains. I do not know if it happens with other ovens or work tables.

**Comment by CJMinecraft01** [comment]
Could you post the console log so I can see if an error has occurred. Also which mod are you using for the slab furnaces?

**Comment by ArturilloD** [comment]
Sorry for not answering yet, I've been working and haven't had much time. As soon as I can I pass the error. Thanks in advance.

**Comment by CJMinecraft01** [comment]
That's fine. Take all the time you need

**Comment by ArturilloD** [comment]
You only have to change the .zip to .rar, since .rar is not supported. It is a video where what happens is shown, there is also an error when mining iron and gold, certain spikes do not extract anything, they just disappear, although I do not know how to discover which mod is causing this, I do not think this is it. Regards.

Here I send a video and the crash report file


[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part01.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741966/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part01.zip)
[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part02.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741967/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part02.zip)
[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part03.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741968/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part03.zip)
[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part04.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741969/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part04.zip)
[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part05.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741970/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part05.zip)
[Minecraft_ 1.15.2 - Un jugador 2020-06-07 13-06-43.part06.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4741971/Minecraft_.1.15.2.-.Un.jugador.2020-06-07.13-06-43.part06.zip)
[crash-2020-06-07_13.08.01-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4741975/crash-2020-06-07_13.08.01-client.txt)

**Comment by CJMinecraft01** [comment]
Please check this is still an issue in the latest version when you can :D

**Comment by ArturilloD** [comment]
Go go go 👏👏 works perfect, I see that apart from fixing that, it no longer crashes and has also corrected the position of the slabs. Congratulations, good work. Now I just need to find the rest, heh.
