### ISSUE TITLE
Blacklist not working as intended

### ISSUE THREAD

**Issue by T4ge** [CJMinecraft01/DoubleSlabs#5]
The new blacklist feature does work to a degree, but there's a minor issue when placing a non-blacklisted slab on a slab that is blacklisted.
![image](https://user-images.githubusercontent.com/8440488/69305560-bb5cd280-0c24-11ea-883b-b9a8b86d075d.png)

> general {
    # The list of slab types and variants to ignore when creating double slabs
    # Example: minecraft:purpur_slab
    # Example: minecraft:stone_slab#variant=cobblestone
    S:"Slab Blacklist" <
        blockcraftery:editable_slab
     >
}

**Comment by T4ge** [comment]
After some additional testing, the blacklist doesn't seem to make a change to this behavior.
I can place any slabs ON a Blockcraftery slab, but I can't place Blockcraftery slabs onto other slabs.

**Comment by CJMinecraft01** [comment]
Sorry for the delay. I've managed to figure out the issue (it's partially due to the variant property that blockcraftery uses for slabs but should be fixed in the latest version)

**Comment by T4ge** [comment]
Awesome, we've just tested it and it works flawlessly.
Thanks a lot for getting around to it!
