### ISSUE TITLE
[1.15.2] Crash on server startup

### ISSUE THREAD

**Issue by NielsPilgaard** [CJMinecraft01/DoubleSlabs#53]
`DoubleSlabs-1.15-2.4.5` seems to crash on server startup. This does not happen on fresh worlds, so I suspect a Double Slab must be placed for it to occur.

Latest log: https://gist.github.com/NillerMedDild/f65013eb52e94bf6d244657bd67fe495
Crash report: https://gist.github.com/NillerMedDild/db663baf83e2cd0e68c3b19a36b63114

**Comment by EtainDelbaeth** [comment]
Hey 
I got the same issue and i play  Minecraft version 1.12. 

Crash report -> [https://gist.github.com/EtainDelbaeth/09d1115abe786094f2d1506cdd027708](url)

**Comment by CJMinecraft01** [comment]
This should hopefully be fixed in the latest version!

**Comment by CJMinecraft01** [comment]
If there are no more issues, I'm going to close this 😄
