### ISSUE TITLE
[Enhancement] 1/2 of the slab & Mixed slabs in Vertical state

### ISSUE THREAD

**Issue by Xelbayria** [CJMinecraft01/DoubleSlabs#55]
Current Version: DoubleSlabs-1.12-0.6.0.jar
Current Forge: forge-14.23.5.2854

Hello, I would like to suggest: 

~~1) add double slabs for vertical where I can place 2 mixed slabs in the vertical state~~
2) using 1/2 of the slab to fill the corner using Vertical slab (Or using 1/4 of the block) 
3) using 4 mixed slabs (1/2 of the slab) into a full block. I'll add the link to show the example. 
4) 1/2 of the slab can be also used to work with a stair

that's it. This will improve your mod more further and also making it very simple to use as well. 

Edit: 
Here's a good example of 3) and 4):
https://imgur.com/a/qasNxom

Edit 2: 
just ignore the (1): vertical slabs (1/2 of the block). I see that the mod already has it. It took me a while to figure it out.

**Comment by CJMinecraft01** [comment]
Thanks for the suggestions! What you're describing seems to be like 1/4 of a block slices I'm assuming? I think these would be really cool additions to Minecraft but I'm not sure how best this would work with my mod, as my mod simply enhances the behaviour of slabs.

One way I could see this being done is through the use of a saw which splits blocks in half but I believe this has been implemented in other mods and I feel that it diverges from the vanilla+ experience I have been going for with my mod.

Please let me know your thoughts and ideas! Again, thank you for the suggestions!

**Comment by Xelbayria** [comment]
Ah, I don't realize that your goal was to enhance the Vanilla+ experiences. you can forget my suggestions. After reading your comment, I had to find another mod that could provide a similar ideal and I found one and it's good enough for now. 

Thanks for replying and I'll just close this suggestion.
