### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by EtainDelbaeth** [CJMinecraft01/DoubleSlabs#56]
Hey 
I got an issue with my Minecraft server 1.12.
I got this Crash log : [https://gist.github.com/EtainDelbaeth/09d1115abe786094f2d1506cdd027708](url)

Bye and thank

**Comment by CritFlaw** [comment]
Getting the same crash

**Comment by agentwolf88** [comment]
https://pastebin.com/028AbByv

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
