### ISSUE TITLE
Blast Proof Slabs

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#58]
The mod [Savage and Ravage](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)  adds a slab and vertical slab that is blast-proof, but that is no longer the case once combined into a double slab.

**Comment by CJMinecraft01** [comment]
Hi, thanks for this report! This has been an oversight on my behalf. Currently the mod uses the smallest blast resistance to use as the blast resistance for the block however I believe it is better to use the larger value for this case. I will change this and add this in the next version!

**Comment by CJMinecraft01** [comment]
Added this in the latest version!
