### ISSUE TITLE
Slime Slabs

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#59]
The mod [Alike Tools](https://www.curseforge.com/minecraft/mc-mods/aliketools) adds in a slime slab, but it is no longer bouncy once combined into a double slab.

**Comment by CJMinecraft01** [comment]
Hi, thanks for this issue. This seems to be an oversight on my side that I hadn't considered slime slabs so I'll add support for this in the next version!

**Comment by WenXin20** [comment]
Thanks!

**Comment by CJMinecraft01** [comment]
Added support for this in the latest version. With vertical slabs, ensure you land on the side which is the slime slab!
