### ISSUE TITLE
[suggestion] Block breaking speed/harvest level depends on which half you're breaking

### ISSUE THREAD

**Issue by yukinagatosc2** [CJMinecraft01/DoubleSlabs#6]
Once klee slab behavior is implemented it'd be nice if the slab you tried to break has the same harvesting behavior that a lone slab would.  i.e. same hardness, explosion resistance and harvest level

**Comment by CJMinecraft01** [comment]
This is now partially implemented. Whilst I don't have the klee slab behaviour yet, the block hardness, harvest level etc. does depend on the slabs which make up a double slab

**Comment by yukinagatosc2** [comment]
nice.  keep up the good work

**Comment by CJMinecraft01** [comment]
This will finally be added in the latest version! The blocks now break separately in survival and the speed of mining the individual slab depends on which tool you are using and for which slab you are targeting!
