### ISSUE TITLE
Double Slabs Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#60]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Double Slabs v2.5.1`

If a double slab is created underwater, it renders incorrectly, with water flowing down it's sides.

**Comment by CJMinecraft01** [comment]
Do you have a screenshot so I can see what you mean please?

**Comment by WenXin20** [comment]
The double slab is a stone bricks and wood planks slab.
![2020-06-17_15 42 01](https://user-images.githubusercontent.com/12000593/85049692-aca6b180-b15a-11ea-96f4-8b8dddbde42f.png)

**Comment by CJMinecraft01** [comment]
Hmm. Okay. Thank you for the report! I will take a look and see what I can do. Not too sure what would be causing this.

**Comment by WenXin20** [comment]
It's similar to how glass used to render underwater. Some mod glass still does this, so it might be related to transparency.

**Comment by CJMinecraft01** [comment]
So I've looked into this and it seems to be due to the fact that a double slab and a vertical slab are not classed as solid blocks to enable compatibility with slabs that have transparency which causes the game to render the flowing water textures on the side. From what I've seen, there is no apparent way to fix this unfortunately but I will continue to investigate

**Comment by WenXin20** [comment]
Hmm, how does glass handle it? Looks like there is a method from forge to avoid that [here](https://github.com/MinecraftForge/MinecraftForge/commit/f93289e01c7a5a36aa8105c5ade2eb8402a6a49c), maybe this'll help?

**Comment by CJMinecraft01** [comment]
That is only applied for the bottom side of the block and not for every side of the block unfortunately

**Comment by WenXin20** [comment]
Hmm, I reported a similar issue at CyclopsMC/ColossalChests#126 at while ago, maybe this will help?

**Comment by CJMinecraft01** [comment]
Hold on, I think you're right. I misread that it was part of a for loop. Whoops :D.
I'll see about patching that right away for you!

**Comment by WenXin20** [comment]
Thanks!
