### ISSUE TITLE
[1.15.2 / 31.1.63] Crash at loading the game/server

### ISSUE THREAD

**Issue by jouki** [CJMinecraft01/DoubleSlabs#61]
Hi,
as the title says.
**Forge version**: 31.1.63 (1.15.2)
**Crash Log**: https://pastebin.com/QWfUdzQ6
**Log Dump**: https://pastebin.com/wC8f6xYv
**Mod List**: https://pastebin.com/JKf5VPti
Client-side has Optifine_pre24

Cheers,
Jouki

**Comment by solarblindfull** [comment]
I have exactly the same crash at the loading of my server. I'm on Forge 31.2.20 with Optifine pre24. The crash occurs with the 2.6.0 version of the mod. Thanks for the report.

**Comment by tslindsay** [comment]
Yep, class loading errors here too with 2.6.0

(Thanks for the work you're putting into getting these issues fixed - this is a great mod!)

**Comment by CJMinecraft01** [comment]
I think this should be fixed in the latest version! Sorry about that!
