### ISSUE TITLE
Placing Crafting Station on Lower-half Slab Crashed Server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [CJMinecraft01/DoubleSlabs#62]
A player, upon attempting attempted to place a crafting station half-slab onto a stone brick slab resulted in a server crash. The stone brick slab was on the lower half of the adjacent block. See screenshot below: 
![2020-06-18_15 58 21](https://user-images.githubusercontent.com/17887664/85076103-c953e100-b17c-11ea-98cb-b90ea25478f1.png)

I'm not sure if this is related to issue: https://github.com/CJMinecraft01/DoubleSlabs/issues/48

While the server did crash, the crash-report did not tell much. However, the latest.log shows the error.

[latest.log](https://github.com/CJMinecraft01/DoubleSlabs/files/4801416/latest.log)
[crash-2020-06-18_23.29.23-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4801417/crash-2020-06-18_23.29.23-server.txt)

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.20
- DoubleSlabs-1.15-2.5.1
- Crafting Station 3.1.0

**Comment by CJMinecraft01** [comment]
Hi! This is related to that issue. If you update to the latest version 2.6.1 it should be fixed. There should be a Crafting Station update soon once my PR is accepted
