### ISSUE TITLE
Vertical Slabs not rendering properly with shaders

### ISSUE THREAD

**Issue by SomeGuyNamedJon** [CJMinecraft01/DoubleSlabs#64]
Top and thin sides of slab will render invisible when placed vertically with shaders enabled through optifine

**Comment by CJMinecraft01** [comment]
Thanks for the report, can you show me a screenshot please and for which mod, Minecraft and OptiFine version are you using?

**Comment by SomeGuyNamedJon** [comment]
![image](https://user-images.githubusercontent.com/60898789/85164477-06c27800-b22a-11ea-8422-bf86c1c0a29e.png)

The block is also completely see through from one of the large faces.

![image](https://user-images.githubusercontent.com/60898789/85164741-6751b500-b22a-11ea-8d2e-7f66a144e3b1.png)

using Optifine 1.14.4 HD U F5 with compatibility through OptiForge (client will crash otherwise without it). Forge version forge-28.2.18. Doesn't matter what shader or resourcepack I use, this is always the result. 

Complete modlist: --------------------------------------------------------------------------
☃ Snow! Real Magic!	Snownee_	SnowRealMagic-1.14.4-1.5.2.jar	

🥝 Kiwi	Snownee_	Kiwi-1.14.4-2.6.3.jar	

Advanced Chimneys	EnderLanky	AdChimneys-1.14.4-4.0.0.1-build.0072.jar	

Carpet Stairs Mod	EndlesNights	carpetstairsmod-mc1.14.4_v1.4.4.jar	

Collective	Serilum	collective-1.14.4-1.23.jar	

Decorative Blocks	stohun	decorative_blocks_6b.jar		

Double Doors	Serilum	doubledoors_1.14-2.1.jar	

Double Slabs	CJMinecraft01	DoubleSlabs-1.14-1.5.0.jar	

Extended Lights	polyvalord	extlights-1.8.jar	

ForgeEndertech	EnderLanky	ForgeEndertech-1.14.4-5.2.2.2-build.0084.jar	

Just Enough Items (JEI)	mezz	jei-1.14.4-6.0.0.27.jar	

Kottle	Alex_wells	Kottle-1.4.0.jar	

Lotta Terracotta	rahalabytes	lottaterracotta-1.14.4-1.3.0.jar	

MixinBootstrap	LX_Gaming	MixinBootstrap-1.0.3.jar	

Nifty	Squiggly_Androsa	nifty-1.14.4-2.8.jar	

OptiForge	ZekerZhayard	OptiForge-MC1.14.4-0.1.1.jar	

Placeable Items	Ferdz_	placeableitems-4.1.1.jar	

Sit	bl4ckscor3	sit-1.14.4-v1.3.jar	

Snow Under Trees	bl4ckscor3	snowundertrees-1.14.4-v1.1.1.jar	

Sweet Concrete	rahalabytes	sweetconcrete-1.14.4-1.7.1.jar	

Torch Slabs Mod	EndlesNights	torchslabmod-1.14.4_v1.5.jar
---------------------------------------------------------------------------------------------

**Comment by SomeGuyNamedJon** [comment]
Upon further testing, the culprit is somewhere along that modlist, testing with only optiforge, optifine, and double slabs does not produce this issue. I'll look into this further.

**Comment by SomeGuyNamedJon** [comment]
Okay... it's not anything in that list. It's something to do with a mod I had installed and removed, but I can't for the life of me figure out what mod that would have been. Gonna keep digging, but I have no clue why this issue occurs and I can't seem to reproduce it through recreating the modpack as is. Gonna have to find what mod I installed and removed caused this issue.

**Comment by CJMinecraft01** [comment]
Please try using the latest version of my mod as I included a specific fix for OptiFine in the update

**Comment by SomeGuyNamedJon** [comment]
Yeah, that fixed it. Wow you work fast. 👍

**Comment by CJMinecraft01** [comment]
I fixed it yesterday 😂 glad that works. Let me know if you have any further issues!
