### ISSUE TITLE
Crash when quickly placing two slabs on top of each other

### ISSUE THREAD

**Issue by tplc10** [CJMinecraft01/DoubleSlabs#66]
Specifically, I had this crash when quickly placing two jasper brick slabs on top of each other in the Valhelsia 2 modpack. 

[crash-2020-06-19_20.29.22-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4807256/crash-2020-06-19_20.29.22-client.txt)
[crash-2020-06-19_20.17.45-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4807257/crash-2020-06-19_20.17.45-client.txt)

**Comment by CJMinecraft01** [comment]
Hi thanks for this bug report! This should be fixed in the latest versions for 1.15/1.14!
