### ISSUE TITLE
Invert Sneak Config Option Works Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#67]
Minecraft v1.15.2
Forge v31.2.19
Double Slabs v2.6.1

After switching the config option `invert_sneak_vertical_slab_placement` to `true`, I found out that it works incorrectly. Vertical slabs will place weather or not I'm holding the shift button, so it always places vertical slabs.

I'm also wondering, would it be possible to have a config option for vertical slabs to place if right-clicking the side of a block, while right-clicking the top/bottom of a block places the horizontal slabs, unless holding shift, which would allow it to place the opposite? That's the way the Lord of the Rings mod does it anyways.

**Comment by CJMinecraft01** [comment]
Hi! Thanks for the report. I'm thinking of favouring an alternate system like the one you suggested as it feels more intuitive which can be disabled using a config option. I may remove the invert sneak option as I feel it might be redundant with the placement as you suggested. Please let me know your thoughts on this!

**Comment by CJMinecraft01** [comment]
This has now been released in the latest 1.14/1.15 version!

**Comment by CJMinecraft01** [comment]
And now for 1.12. Please let me know your thoughts on the new system!

**Comment by WenXin20** [comment]
Thanks! I'll give it a try!
