### ISSUE TITLE
Placing a vertical slab inside block makes it dissapear

### ISSUE THREAD

**Issue by Phyksar** [CJMinecraft01/DoubleSlabs#68]
Using latest version 2.7.1 at the moment, game version 1.15.2, Forge 31.2.21. No other mods installled.
![ezgif-4-7c6ff28472e8](https://user-images.githubusercontent.com/13320416/85213098-94a17e80-b362-11ea-86ec-1ebcdf1beae0.gif)

**Comment by CJMinecraft01** [comment]
Well erm that was unexpected. I'll get to fixing that as soon as I can!

**Comment by CJMinecraft01** [comment]
Fixed in the latest version
