### ISSUE TITLE
Crash when placing a slab on the upper half of a block

### ISSUE THREAD

**Issue by Lithobraker** [CJMinecraft01/DoubleSlabs#69]
[crash-2020-06-21_02.47.14-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4809012/crash-2020-06-21_02.47.14-client.txt)
![2020-06-21_02 47 07](https://user-images.githubusercontent.com/6070905/85218584-9cb0ec80-b369-11ea-9225-25717d118e16.png)
Just as the title says here. I place a slab on the upper half of this block, and the game hard crashes.
This crash is 100% consistent, and happens every single time.
Judging by the log, this could be a FoamFix issue, but I'm not very experienced at reading these things. Haven't yet tried it without FoamFix.
Edit: The crash still occurs without FoamFix enabled.
[crash-2020-06-21_02.54.03-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4809017/crash-2020-06-21_02.54.03-client.txt)

**Comment by CJMinecraft01** [comment]
Hmm. That is very strange. I'll take a further look and see if I can fix this

**Comment by CJMinecraft01** [comment]
Please try this in the latest version as I think I may have fixed it :)

**Comment by Lithobraker** [comment]
> 
> 
> Please try this in the latest version as I think I may have fixed it :)

Really sorry I didn't get back to you sooner- very distracted- but it does seem to have worked!
Very cool stuff. I'll be glad to include this mod in my pack!
![2020-06-28_22 44 10](https://user-images.githubusercontent.com/6070905/85967633-ed8b9b00-b990-11ea-8d5b-6a668269866e.png)

**Comment by CJMinecraft01** [comment]
Glad it is fixed! Sorry about that :)
