### ISSUE TITLE
Crash when an entity or a player walks to a vertical slab.

### ISSUE THREAD

**Issue by AxolotlAccount** [CJMinecraft01/DoubleSlabs#70]
Minecraft Version: 1.12.2
Mod Version: DoubleSlabs-1.12-0.7.1
Forge Version: 14.23.5.2854
Crash Report: https://hastebin.com/yikeseguju.php

Description: Game crashes when an entity or a player touches to a vertical slab. This crash occurs again instantly when you enter your world back.

**Comment by DavidosWolfe667** [comment]
I have removed all surrounding blocks, and it seems the crashing has stopped. I will start adding the setup of blocks I had 1 by 1 to see what is causing the crash.

**Comment by DavidosWolfe667** [comment]
I've cleared every block around it except for the slabs and it still crashes, so it's entirely dependant on going from a top slab block to the vertical double slab.

**Comment by DavidosWolfe667** [comment]
Started a completely new world with a different tile set to rebuild, and it crashed under the exact same circumstances as above.
So even vanilla tilesets will do this.
[crash-2020-06-26_20.41.39-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4838735/crash-2020-06-26_20.41.39-client.txt)
[crash-2020-06-26_20.40.30-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4838736/crash-2020-06-26_20.40.30-client.txt)

**Comment by CJMinecraft01** [comment]
Please try this in the latest version as hopefully this time I've fixed it :D
