### ISSUE TITLE
Crash while walking over vertically placed slab.

### ISSUE THREAD

**Issue by DavidosWolfe667** [CJMinecraft01/DoubleSlabs#73]
Playing on Engineer's Life, got sick of not being able to combine slabs.

Seems to be triggered after walking over vertical planks.

See attached log.
[crash-2020-06-26_00.09.12-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4834067/crash-2020-06-26_00.09.12-client.txt)
[crash-2020-06-26_00.05.54-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4834068/crash-2020-06-26_00.05.54-client.txt)

**Comment by DavidosWolfe667** [comment]
Seems a very specific doorway only, any other passage way works, I don't get it.

**Comment by CJMinecraft01** [comment]
This is a duplicate of #70
