### ISSUE TITLE
Configuration file not generating on servers

### ISSUE THREAD

**Issue by toontownlpz** [CJMinecraft01/DoubleSlabs#75]
I had to downgrade my modpack's version of Double Slabs to v2.6.1, as it seemed to me that v2.7.0 and above would not generate the config file correctly. This is important for my modpack as I do not have vertical slab placement enabled. Not really sure how to provide results to recreate this, but if you want you can use my modpack to test.

Simply download the latest version of my modpack from [here](https://www.curseforge.com/minecraft/modpacks/bees-and-beyond), update Double Slabs to the latest version, and then run a server running Double Slabs v2.7.0 or above. Doesn't seem to generate a config file or even read existing ones.

**Comment by CJMinecraft01** [comment]
Have you checked the serverconfig folder? Inside there should be the doubleslabs-server.toml config file

**Comment by toontownlpz** [comment]
Ah, I see. Is there a reason for this? It seems like you now have to set them based on the world rather than the entirety of Minecraft. If that's the case, I guess I can just stick with Double Slabs v2.6.1.

**Comment by CJMinecraft01** [comment]
The reason is intended for servers owners as the way the placement mechanism works, both the client and the server need to have the same placement options, so if say vertical slabs are disabled on the server, they should also be disabled on the client. By making this a server config, this is done automatically by forge without me needing to sync it over. I feel that ultimately this is the better move in my opinion for consistency sake.

**Comment by toontownlpz** [comment]
So to clarify, should I stick with v2.6.1? Both the client and server are supposed to have vertical slab placement disabled full-stop.

**Comment by CJMinecraft01** [comment]
That depends on your preference. I personally would recommend continuing to update as I no doubt fix bugs and add new features but I respect the fact that it is easier to have a global config for all worlds. I may take a look at adding a way to do so but I want the config to be consistent (and not have the same option appear in two places) if you get what I mean?

**Comment by toontownlpz** [comment]
I would appreciate if you could potentially implement a choice for either, as due to my modpack's intent I've deliberately disabled vertical slab placement on both the client and server packs that are available for download. I just find this easier as it requires less intervention from users looking to play using my modpack, whereas with the newer versions I'd have to expect them to make the change themselves in their worlds. Either way, I appreciate the mod! For the time being however I will stick with v2.6.1.

**Comment by CJMinecraft01** [comment]
Upon further investigation I've discovered that this is actually available in forge already. Simply place the doubleslabs-server.toml file that you want to be default, into the defaultconfigs folder in the root directory and that should give you the desired outcome!

**Comment by toontownlpz** [comment]
Hey, I've tried what you suggested and it does indeed work! However, there's an issue. My modpack is designed to be easy to use and upgrade to newer versions when desired, but when you move an existing world over to the new server pack with the defaultconfigs folder being used, it doesn't copy the defaultconfig folder's contents over to the existing world.

Any way to fix that? I don't know if this is a big deal, but the config for the client's side seems to override the config for the server's side, which is okay, but causes some visual disturbance when trying to place a vertical slab on a server with vertical slabs enabled whilst the client has them disabled.

**Comment by CJMinecraft01** [comment]
I'm not sure there is a direct way to fix that unfortunately without instructing people to copy over the config to their world. And the second issue regarding the client and a weird visual disturbance is the reason I moved it over to the server config to resolve that issue. I'm not too sure what else to recommend, as I completely understand your position. If the config is not present though in the world file (as it has not been updated) then it should create one using the default config you provide. It will only affect those who have updated Double Slabs already

**Comment by toontownlpz** [comment]
I'm close to updating my modpack with the newest Double Slabs release, however I have one issue. The contents of the 'defaultconfigs' folder does not get copied over to new worlds automatically when I start up a new server. Any way to combat that?

I am essentially dealing with this same issue, except it just doesn't copy the defaultconfigs files into the server's worlds: https://github.com/MinecraftForge/MinecraftForge/issues/6541

To clarify, 'defaultconfigs' works fine on the client. Every new world I make copies the 'doubleslabs-server.toml' file and it works as needed, but new servers just outright refuse to copy this same file over.

**Comment by toontownlpz** [comment]
If you would like to test this using my modpack, you can find a 'beta' release with these changes here: https://www.curseforge.com/minecraft/modpacks/bees-and-beyond/files/2991267

Both client and server packs are offered.

**Comment by CJMinecraft01** [comment]
Hi. Thank you for sending the link. In the download for the server, it has the old double slabs jar (2.6.1) and not the new one. When testing with the new one on an old world (generated using DoubleSlabs 2.6.1) the server config was added automatically (as it was not present in the old world) and so the vertical slabs were disabled. Like you said, creating a new world on the client works fine and I'm assuming it will work on an old world which is updated. I've also tested creating a new world on the server and this too works correctly with the new file being copied over so I think everything is working as expected. Let me know if you have any further issues :)

**Comment by toontownlpz** [comment]
Sometimes I am unable to comprehend my own stupidity. Thank you for helping me fix this! Of course, updating the mod on the server fixed it... I mean, why wouldn't it? -_-

I have now released my modpack update: https://www.curseforge.com/minecraft/modpacks/bees-and-beyond/files/2991944

**Comment by CJMinecraft01** [comment]
Fantastic. Glad to hear it is working for you and all the best with you modpack. Seems pretty neat!

**Comment by toontownlpz** [comment]
Thank you!
