### ISSUE TITLE
Light Bug

### ISSUE THREAD

**Issue by WormaxPL** [CJMinecraft01/DoubleSlabs#77]
This bug is a huge problem for me as builder... Since I start using this mod in my modpack i have this bug... I don't  know is that a mods collision or something else, but sometimes near this dark area monsters (like creepers) can spawn. I love this mod because I really want vertical slabs in Minecraft! Please fix this

![2020-07-01_17 34 24](https://user-images.githubusercontent.com/67701059/86263399-7721af80-bbc1-11ea-9c9d-7a4f9473ca65.png)
![2020-07-01_17 34 48](https://user-images.githubusercontent.com/67701059/86263406-78eb7300-bbc1-11ea-85f6-7c5ff8521b9b.png)
![2020-07-01_17 35 36](https://user-images.githubusercontent.com/67701059/86263410-79840980-bbc1-11ea-8111-21691a0901e6.png)

**Comment by CJMinecraft01** [comment]
Which version of my mod are you using?

**Comment by WormaxPL** [comment]
> Which version of my mod are you using?

It's a DoubleSlabs-1.12-0.7.4 but i have this bug since i start using this mod at version 0.7.2

**Comment by CJMinecraft01** [comment]
Thanks for reporting this. I believe the issue you're seeing here is due to an effect known as ambient occlusion. If you turn your graphics settings to not have smooth lighting I believe this goes away (this would be a temporary fix). I'll take a look and see what I can do

**Comment by WormaxPL** [comment]
> Thanks for reporting this. I believe the issue you're seeing here is due to an effect known as ambient occlusion. If you turn your graphics settings to not have smooth lighting I believe this goes away (this would be a temporary fix). I'll take a look and see what I can do

Okey. Thanks for advice and good luck with working at this

**Comment by CJMinecraft01** [comment]
Quick question, do you have OptiFine installed?

**Comment by WormaxPL** [comment]
> Quick question, do you have OptiFine installed?

Yes, I do

**Comment by CJMinecraft01** [comment]
Does the error occur when OptiFine is not installed?

**Comment by WormaxPL** [comment]
> Does the error occur when OptiFine is not installed?

I don't know... I don't launch any mods without Optifine installed

**Comment by CanINotUseTruth** [comment]
So I have the same issue with the version DoubleSlabs-1.12-0.7.4, I get similar issues to the pictures above with Optifine installed. When Optifine is disabled it still has a slight issue with the lighting but not as bad and yes Smooth Lighting off is a temporary fix, exclusively happening with vertical slabs :) Pictured below is the effect when Optifine is not installed but Smooth Lighting is Max.

![2020-07-08_00 20 59](https://user-images.githubusercontent.com/32658931/86795666-24f4f880-c0b1-11ea-90aa-cb53df1c8e5d.png)

**Comment by CJMinecraft01** [comment]
I have improved this further in the next update. Whilst not entirely fixed, the shading should be better for vertical slabs.
*Note: when OptiFine is installed, I have to remove a fix for shading which gives the line on the top of vertical slabs if a block is underneath as otherwise the block appears invisible. The fix simply reorders the vertices so that the ambient occlusion is aligned but unfortunately, whilst this fixes it for when OptiFine is not installed, when installed the error still occurs*

**Comment by WormaxPL** [comment]
> I have improved this further in the next update. Whilst not entirely fixed, the shading should be better for vertical slabs.
> _Note: when OptiFine is installed, I have to remove a fix for shading which gives the line on the top of vertical slabs if a block is underneath as otherwise the block appears invisible. The fix simply reorders the vertices so that the ambient occlusion is aligned but unfortunately, whilst this fixes it for when OptiFine is not installed, when installed the error still occurs_

I understand... Thanks for your time

**Comment by CJMinecraft01** [comment]
Hi there! I know that it's been a while and I sincerely apologise for that; however I have some great news!! I have finally managed to fix this issue and now the vertical slab lighting will be correct! For now this is exclusive to 1.16 only; however I will be backporting this gradually. Thanks for your patience :)

**Comment by WormaxPL** [comment]
> Hi there! I know that it's been a while and I sincerely apologise for that; however I have some great news!! I have finally managed to fix this issue and now the vertical slab lighting will be correct! For now this is exclusive to 1.16 only; however I will be backporting this gradually. Thanks for your patience :)

Nice to hear that. Thanks!
