### ISSUE TITLE
Lotta Terracota compatibility issues

### ISSUE THREAD

**Issue by Dabreu131** [CJMinecraft01/DoubleSlabs#79]
The Lotta Terracota vertical slabs don't seem to work with the double vertical slab feature. I have disabled the vertical placement feature for regular slabs.

**Comment by Angela** [comment]
@CJMinecraft01 are you open to pull requests? If so, I am happy to do the work to add support for my two mods [Lotta Terracotta](https://github.com/RahalaBytes/LottaTerracotta)/[Sweet Concrete](https://github.com/RahalaBytes/SweetConcrete).

**Comment by CJMinecraft01** [comment]
Yes I am open for pull requests! You might find it useful to use my `VerticalSlabSupport` class as that generalises vertical slabs so you only need to give the names of the classes for reflection

**Comment by CJMinecraft01** [comment]
This has been added in the latest version!
