### ISSUE TITLE
Incorrect Breaking Texture

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#80]
Minecraft v1.15.2
Forge v31.2.31
Double Slabs v2.7.6

When breaking a vertical slab, the breaking texture appears incorrectly. I also sometimes see a missing texture after the block is broken for half a second. Also, Immersive Portals is not installed.

![2020-07-09_00 54 56](https://user-images.githubusercontent.com/12000593/87004554-39a1c100-c183-11ea-8e92-47ff27070fc1.png)

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest versions!

**Comment by WenXin20** [comment]
Thanks!
