### ISSUE TITLE
Valhelsia 2 Crashes

### ISSUE THREAD

**Issue by 0mayor** [CJMinecraft01/DoubleSlabs#81]
Hey! So I use this mod in the modpack Valhelisa 2 and it's the reason I've been having countless crashes recently. Here's the pastebin, just wanted this to be known! https://pastebin.com/Az39vC1Z

**Comment by CJMinecraft01** [comment]
Hi! Thanks for the report. Which slabs were you combining so I can check whether the support is correct

**Comment by 0mayor** [comment]
> Hi! Thanks for the report. Which slabs were you combining so I can check whether the support is correct

I was using EmbellishCraft Old Brick Slabs, Vertical Brick Slabs from Quark and just regular Brick Slabs but with the shift ability to place them vertically. There was a lot of mix and matching...

**Comment by CJMinecraft01** [comment]
Thank you. I'll take a look and see if I can get this fixed as soon as possible!

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version!
