### ISSUE TITLE
Clicking a block that under a vertical slab generates/drops random botania pebbels.

### ISSUE THREAD

**Issue by SMHerobrine** [CJMinecraft01/DoubleSlabs#82]
Clicking a block that under a vertical slab generates/drops random botania pebbels.

**Comment by CJMinecraft01** [comment]
Hi thanks for the issue! Sorry for the late response, which Minecraft and mod version is this using? I'm assuming MC 1.12?

**Comment by SMHerobrine** [comment]
Yes 1.12.2


Kontakt CJMinecraft (<notifications@github.com>) kirjutas kuupäeval K, 15.
juuli 2020 kell 11:28:

**Comment by SMHerobrine** [comment]
Yes 1.12.2

**Comment by CJMinecraft01** [comment]
Hi, please check but I think this may be fixed in the latest version :)

**Comment by SMHerobrine** [comment]
Nope still dropping botania pebbels.

**Comment by CJMinecraft01** [comment]
Hi, sorry about that. How do you get pebbles to spawn using botania? I tried in a test world and it wouldn't spawn any so I'd assumed it was fixed

**Comment by SMHerobrine** [comment]
1) have double slabs and botania installed
2) place a vertical slab by sneaking
3) Place the vertical slab
4) click on the block what is under the vertical (press with the key what places block) + be sneaking while clicking

See it in action: https://www.youtube.com/watch?v=70m4vwEP-Ds

**Comment by CJMinecraft01** [comment]
I'm assuming the behaviour you was expecting was that it would place the vertical slab? If so, vertical slabs can only be combined when not holding shift as holding shift would place the slab horizontally against that block. As you are standing there, it is highly likely that you are simply sneak right clicking on the grass block which is dropping the pebbles

**Comment by SMHerobrine** [comment]
Yep you right.
