### ISSUE TITLE
Compatibility with XNet facade's

### ISSUE THREAD

**Issue by Jaeiya** [CJMinecraft01/DoubleSlabs#84]
Currently if you try to place an XNet facade that has been set to mimic a vertical slab, it will crash the game.

**Comment by CJMinecraft01** [comment]
Do you have the crash log please? And for which Minecraft and mod version is this for?

**Comment by Jaeiya** [comment]
Minecraft version 1.15
DoubleSlabs version 2.8.2

Crash log:
[crash-2020-07-15_14.24.09-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4934141/crash-2020-07-15_14.24.09-client.txt)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!

**Comment by Jaeiya** [comment]
Thanks, I really appreciate it
