### ISSUE TITLE
Request: add config option or keybind for kleeslabs-like functionality in creative mode

### ISSUE THREAD

**Issue by MCXopjesh** [CJMinecraft01/DoubleSlabs#85]
Hi, so I found this mod recently, and I am a big fan of what you have done! I think it is the best slab mod I have found! As the title suggests, I'd like to request a keybind or config option for kleeslabs-like functionality in creative mode. I know that functionality is already in survival mode, but speaking as someone who primarily uses creative mode, I would love to have that feature added to it in some sort of way. With a keybind, I could quickly switch between editing half slabs and whole blocks. If for whatever reason a keybind can't happen, a config option would also be great! Anyways, that's my request, I hope you will consider it! Thanks for making this awesome mod!

**Comment by MCXopjesh** [comment]
For some reason, the curseforge comment section skipped my mind when I was commenting this, sorry if this was the wrong place to put this!

**Comment by CJMinecraft01** [comment]
Hi! Thanks for the report. This is the correct place to put it :). Do you reckon it would be okay to simply have it so that if you are sneaking it doesn't break both or do you think it'd be better to make it so if you aren't sneaking it breaks both by default? (Maybe an option to choose which preference). Please let me know your thoughts :)

**Comment by MCXopjesh** [comment]
I think sneaking should make it break half! I think that is a good idea! My only concern is that often I am flying in creative mode, and while it is possible to sneak while flying, it's a little more annoying. But that's a minor inconvenience, and I do think the sneak functionality is a good idea!

**Comment by CJMinecraft01** [comment]
Yeah I get your point regarding flying as I have experience this myself but hopefully the sneak check should be sufficient. This should be available as soon as I release the next version :)

**Comment by MCXopjesh** [comment]
Awesome! Thanks dude!
