### ISSUE TITLE
Support for extinguished campfires

### ISSUE THREAD

**Issue by agr21** [CJMinecraft01/DoubleSlabs#88]

**Comment by CJMinecraft01** [comment]
What do you think about this? It has all the normal campfire functionality but can be combined with slabs (and even vertical slabs)
![image](https://user-images.githubusercontent.com/13885569/88268772-dfe4df00-ccca-11ea-86e0-fe92d04bec4d.png)

**Comment by agr21** [comment]
it looks great! i can even stack them on each other. though now the ones on the slab or vertically placed cant be extinguished now. (also for me they are "dark" and dont emit light,but it can be a problem with me specifically)

**Comment by CJMinecraft01** [comment]
Thanks. Could you show me a screenshot of how they look? I understand that they don't emit light (this isn't a supported feature yet)

**Comment by agr21** [comment]
![2020-07-23_15 09 52](https://user-images.githubusercontent.com/62674078/88290265-c6598c80-ccf6-11ea-9f93-cbdfa4176ab2.png)
not emitting light is fine imo,and apart from that they look good
and i add,works fine with soul campfires too!

**Comment by CJMinecraft01** [comment]
Nice. I think the lighting is due to the fact that they don't emit light and that you have shaders enabled. Once light support is enabled (as some slabs may have emit light) it should work perfectly :)

**Comment by agr21** [comment]
hope so! thanks for your work, its great! :)

**Comment by CJMinecraft01** [comment]
No problem :+1:

**Comment by WenXin20** [comment]
Hello, I've noticed that campfires can't be extinguished with a shovel or when placed in water if it is a double slab. It also doesn't damage entities when it's lit. It also won't place sideways in water.

**Comment by CJMinecraft01** [comment]
Fixed in the latest version :)
