### ISSUE TITLE
Crash when breaking top half of double slab when theres a slab on top

### ISSUE THREAD

**Issue by NICHOLAS85** [CJMinecraft01/DoubleSlabs#89]
Hello! I am currently running a 1.12.2 Forge server and tried adding this mod to the pack. When I tested this with an alternating tower of wood and cobblestone slabs I find that when I break a top half slab in this tower my client crashes, although the server keeps running. I tried adding this mod to [this mod pack ](https://www.curseforge.com/minecraft/modpacks/jasb-just-another-skyblock/) so there's most likely a mod conflict. If you happen to know whats going on that'd be great! Heres a log:
[crashlog.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4963190/crashlog.txt)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!

**Comment by NICHOLAS85** [comment]
Was able to confirm the latest version no longer crashes, thanks!
