### ISSUE TITLE
Game Freeze with Hywla

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#9]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Hwyla v1.10.6-B67`
`Double Slabs v1.0.1`

The game froze after creating a double slab out of just two spruce slabs.
[Log](https://gist.github.com/WenXin20/3e2250bd63ccbefe0a5239e0583389ad)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version
