### ISSUE TITLE
Vertical slabs place instead of replacing tall grass

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#91]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Double Slabs v2.9.0`

When I right-click on the side of tall grass, it will instead place a vertical slab next to the tall grass.

**Comment by CJMinecraft01** [comment]
I'm assuming that this should replace the grass with the slab?

**Comment by WenXin20** [comment]
Yeah

**Comment by CJMinecraft01** [comment]
Fixed in the latest 1.15 and 1.16 versions. Will be backporting to older versions

**Comment by CJMinecraft01** [comment]
Completely backported now and fixed :)
