### ISSUE TITLE
Crash with snow ?

### ISSUE THREAD

**Issue by AechtRob** [CJMinecraft01/DoubleSlabs#92]
I think this crash is caused by snow layers?
[crash-2020-07-27_18.54.26-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4983969/crash-2020-07-27_18.54.26-server.txt)

Setting double-slabs down is fine. When it snows (eg. using Serene Seasons), the doubled-slabs render with the "broken" texture pattern (purple/black chequers), and within seconds of loading a chunk containing said double slabs with snow the error linked above happens and the server crashes and dies completely. In a single-player setup the broken texture appears but there is no fatal crash afaik.

**Comment by AechtRob** [comment]
Ah, this was using MC 1.12.2 - it's in the log I think?

**Comment by CJMinecraft01** [comment]
Sorry thanks :)

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version :)
