### ISSUE TITLE
[Suggestion-1.16.1] Add a blacklist config to allow disabling slabs to be placed Vertically.

### ISSUE THREAD

**Issue by Gbergz** [CJMinecraft01/DoubleSlabs#94]
Title^
Add a blacklist config to allow disabling slabs to be placed Vertically. Instead of an all On / Off config option. Would be helpful!
Using MC 1.16.1

Kind of like this that already exist but for Vertical Slabs
```	
#The list of slab types and variants to ignore when creating double slabs
#Example: minecraft:purpur_slab

**Comment by Gbergz** [comment]
Saw you just released an update that includes this, just wanted to say thanks! :) 👍

**Comment by CJMinecraft01** [comment]
No problem!
