### ISSUE TITLE
Mod not compatible with Effortless Building 1.12.2

### ISSUE THREAD

**Issue by SnikesBlue** [CJMinecraft01/DoubleSlabs#95]
As mentioned in the title and on the curseforge page, would love compatibility with the options and features that the Effortless Building mod adds, so that there wouldn't be gaps in between slabs when creating lines, diagonals, spheres, walls, cylinders and so on.
Thanks! :)

**Comment by CJMinecraft01** [comment]
Hmm. I'm not too sure how I can add this compatibility as from what I've seen, Effortless Building simply enhances the way you place blocks. If you are selecting a slab, it will by default place only one side of the slab which is something I can't change. I feel it might be better to create this issue on their page. I don't believe the mod is incompatible but rather has an oversight when it comes to the placement of slabs

**Comment by SnikesBlue** [comment]
That's fine, I tried reaching out to them, without luck, but no matter, just the fact that you've added compatibility with Conquest did wonders so far, thanks anyway!
