### ISSUE TITLE
Disappearing slabs when stacked in one block in 1.16.1

### ISSUE THREAD

**Issue by archonsd** [CJMinecraft01/DoubleSlabs#96]
I'm losing the top slab when I stack two slabs of different materials horizontally in the same single block.  The bottom slab is "mahogany" from "Oh the Biomes You'll Go", and the top slab is a Redwood slab, also from the same mod.  If I break the top (Redwood) slab, it shows the anim for breaking, but no slab item is left in the world for pickup.  It's completely reproducible.  This is an SMP server I run.

 - Forge 1.16.1-32.0.77

 - "Oh the Biomes You'll Go" version "byg-1.0.12.jar"

 - "Double Slabs" version "DoubleSlabs-1.16-3.2.0.jar"

My complete mod list is in pastebin [here](https://pastebin.com/1AuccD8g).

**Comment by CJMinecraft01** [comment]
Hi! Thanks for the issue. I'll take a look as soon as I'm back on my PC. Seems like a very unusual issue. Does anything appear odd in the console log?

**Comment by archonsd** [comment]
> Hi! Thanks for the issue. I'll take a look as soon as I'm back on my PC. Seems like a very unusual issue. Does anything appear odd in the console log?

There's a LOT of stuff in the console log, but Forge is still Alpha, so I expect a lot of garbage in the log.  Would providing any of the logs help?

**Comment by CJMinecraft01** [comment]
Yes. Providing the debug.log for when this happened would be great if you can!

**Comment by archonsd** [comment]
Will do.  I’ll blow the old, lengthy debug.log away, restart the server, and repro the steps, so the debug.log is as short an relevant as I can make it.  Coming up.


  *   A

**Comment by archonsd** [comment]
> Yes. Providing the debug.log for when this happened would be great if you can!

I don't see a way to upload a file here, and pasting it in here is too long..  so here's a pastebin of the log.  https://pastebin.com/nbE01Mrd  If you need the actual file, I can throw it in OneDrive and link to it.

**Comment by archonsd** [comment]
I literally just caused it to happen before logging off and pulling the debug.log file.  So it should be right near the bottom.

**Comment by CJMinecraft01** [comment]
Hi! Please try updating to the latest version as from my testing, this appears to be fixed :) (note I tested with just BYG, the issue you are experiencing may be due to immersive portals being installed)

**Comment by archonsd** [comment]
Will do.  Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CJMinecraft01** [comment]
Assuming this has now been fixed
