### ISSUE TITLE
Crash w/ Optifine

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#97]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Double Slabs v2.10.0`
`Optifine pre30`

After updating to the newest version of Double Slabs, my game now crashes immediately after rendering the double slabs. Seems to be related to Optifine.
[Crash Report](https://gist.github.com/WenXin20/266492023a3b647f2bd6d0d8f5925ac0)

**Comment by CJMinecraft01** [comment]
The crash report link doesn't seem to be working unfortunately

**Comment by WenXin20** [comment]
Whoops, forgot to actually include the link. :D
Should be fixed now.

**Comment by TheOrionsun** [comment]
Same here with Forge v31.2.36 the only difference...

**Comment by CJMinecraft01** [comment]
Fixed in the latest version for 1.15.2. Tested in the same environment you provided :)

**Comment by TheOrionsun** [comment]
Thank you
