### ISSUE TITLE
Strange Visual Bug with Optifine

### ISSUE THREAD

**Issue by Camawama** [CJMinecraft01/DoubleSlabs#98]
Latest Version of the Mod and Optifine. When a slab is placed atop another, a bunch of weird graphical bugs can be seen (water goes invisible, plants look weird) until the slabs are broken.

**Comment by CJMinecraft01** [comment]
Do you have a screenshot and which version of the mod, and Minecraft version? Does this happen in the version before?

**Comment by SirBobb** [comment]
please please PLEEEEASE fix it. I use shaders a lot and it's extremely annoying

**Comment by CJMinecraft01** [comment]
Could you provide more information about the issue like a screenshot and which Minecraft and mod version you are using?
