### ISSUE TITLE
Optifine incompatibility during render regions feature[1.16.1]

### ISSUE THREAD

**Issue by WolfaRRR** [CJMinecraft01/DoubleSlabs#99]
Whenever you place 2 slabs onto each other (doesn't matter if they are same or different) there appears an OpenGL error. It happens only when you have **RENDER REGIONS: ON** with Optifine. Well what I've experienced so far, when you have a big build filled with slabs, it breaks some of the chunks entirely and "removes" blocks from another. You can see this on the screenshots below. When you place random 2 slabs somewhere in nature, error still appears, but there is no graphical bug. Tried in fresh new world, happens, too.

**Versions:**
Minecraft 1.16.1
OptiFine 1.16.1 HD U G2
Forge 32.0.105 (I guess this is not relevant since it happens on older versions, too)
DoubleSlabs 1.16-3.3.3

**Debug log is full of:**
_[06Srp2020 10:22:43.669] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_textured_lit (none), at: pre-useProgram
[06Srp2020 10:22:43.672] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_water (none), at: pre-useProgram
[06Srp2020 10:22:43.673] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_textured_lit (none), at: pre-useProgram
[06Srp2020 10:22:43.677] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_water (none), at: pre-useProgram_

It keeps repeating until you move to a location where no double slabs are placed or you disable render regions feature

**On the screenshots below, you can see what happens when I slightly move a mouse:**
![2020-08-07_11 50 24](https://user-images.githubusercontent.com/69346539/89634507-cedcc600-d8a5-11ea-82c0-0e4d29242812.png)
![2020-08-07_11 50 27](https://user-images.githubusercontent.com/69346539/89634519-d2704d00-d8a5-11ea-9315-3b578ea8393e.png)

It would be nice to have this bug fixed since I think a lot of people use Optifine and Double Slabs and render distance feature rids of the annoying vanilla rendering and gives you so much FPS boost. If you need more information, I'll try to answer as soon as possible.

Thank you in advance for solving. 
Wolf

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the extremely delayed response.. I have some great news! This is finally fixed!!! For now it is only for 1.16 but I will be backporting to older versions as soon as I can :)
